/* ex: set ro ft=c: -*- mode: c; buffer-read-only: t -*- */
/* Generated by re2c 3.1 */
#line 1 "implicit.re"
/*
 * implicit.re
 *
 * $Author: why $
 * $Date: 2005/11/13 23:43:56 $
 *
 * Copyright (C) 2003 why the lucky stiff
 */

#include "syck.h"
#include <string.h>

#define YYCTYPE     char
#define YYCURSOR    cursor
#define YYMARKER    marker
#define YYLIMIT     limit
#define YYFILL(n)   {}

void
try_tag_implicit( SyckNode *n, int taguri )
{
    const char *tid = "";
    switch ( n->kind )
    {
        case syck_str_kind:
            tid = syck_match_implicit( n->data.str->ptr, n->data.str->len );
            break;

        case syck_seq_kind:
            tid = "seq";
            break;

        case syck_map_kind:
            tid = "map";
            break;

        default:
            break;
    }
    if ( n->type_id != NULL ) {
       S_FREE( n->type_id );
    }
    if ( taguri == 1 )
    {
        n->type_id = syck_taguri( YAML_DOMAIN, tid, strlen( tid ) );
    } else {
        n->type_id = syck_strndup( tid, strlen( tid ) );
    }
}

const char *syck_match_implicit( const char *str, size_t len )
{
    char *marker;
    char *cursor = (char *)str;
    const char *limit = str + len;


#line 61 "implicit.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 26) YYFILL(26);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy1;
		case '+': goto yy4;
		case '-': goto yy5;
		case '.': goto yy6;
		case '0': goto yy7;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy8;
		case '<': goto yy9;
		case '=': goto yy10;
		case 'F': goto yy11;
		case 'N': goto yy12;
		case 'O': goto yy13;
		case 'T': goto yy14;
		case 'Y': goto yy15;
		case 'f': goto yy16;
		case 'n': goto yy17;
		case 'o': goto yy18;
		case 't': goto yy19;
		case 'y': goto yy20;
		case '~': goto yy21;
		default: goto yy2;
	}
yy1:
	++YYCURSOR;
#line 94 "implicit.re"
	{   return "null"; }
#line 100 "implicit.c"
yy2:
	++YYCURSOR;
yy3:
#line 116 "implicit.re"
	{   return "str"; }
#line 106 "implicit.c"
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy22;
		case '0': goto yy24;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy25;
		default: goto yy3;
	}
yy5:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy27;
		case '0': goto yy24;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy25;
		default: goto yy3;
	}
yy6:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'I': goto yy28;
		case 'N': goto yy29;
		case 'i': goto yy30;
		case 'n': goto yy31;
		default: goto yy3;
	}
yy7:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 0x00: goto yy32;
		case ',': goto yy33;
		case '.': goto yy35;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7': goto yy36;
		case '8':
		case '9': goto yy37;
		case ':': goto yy38;
		case 'o': goto yy39;
		case 'x': goto yy40;
		default: goto yy3;
	}
yy8:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 0x00: goto yy32;
		case ',': goto yy25;
		case '.': goto yy35;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy41;
		case ':': goto yy38;
		default: goto yy3;
	}
yy9:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '<': goto yy42;
		default: goto yy3;
	}
yy10:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy43;
	goto yy3;
yy11:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'A': goto yy44;
		case 'a': goto yy45;
		default: goto yy3;
	}
yy12:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'O':
		case 'o': goto yy46;
		case 'U': goto yy47;
		case 'u': goto yy48;
		default: goto yy3;
	}
yy13:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'F': goto yy49;
		case 'N':
		case 'n': goto yy50;
		case 'f': goto yy51;
		default: goto yy3;
	}
yy14:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'R': goto yy52;
		case 'r': goto yy53;
		default: goto yy3;
	}
yy15:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'E': goto yy54;
		case 'e': goto yy55;
		default: goto yy3;
	}
yy16:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'a': goto yy45;
		default: goto yy3;
	}
yy17:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'o': goto yy46;
		case 'u': goto yy48;
		default: goto yy3;
	}
yy18:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'f': goto yy51;
		case 'n': goto yy50;
		default: goto yy3;
	}
yy19:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'r': goto yy53;
		default: goto yy3;
	}
yy20:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'e': goto yy55;
		default: goto yy3;
	}
yy21:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy1;
	goto yy3;
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I': goto yy28;
		case 'i': goto yy30;
		default: goto yy23;
	}
yy23:
	YYCURSOR = YYMARKER;
	goto yy3;
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy32;
		case 'o': goto yy39;
		case 'x': goto yy40;
		default: goto yy34;
	}
yy25:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy26:
	switch (yych) {
		case 0x00: goto yy32;
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy25;
		case '.': goto yy35;
		case ':': goto yy38;
		default: goto yy23;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'I': goto yy58;
		case 'i': goto yy59;
		default: goto yy23;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N': goto yy60;
		case 'n': goto yy61;
		default: goto yy23;
	}
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A':
		case 'a': goto yy62;
		default: goto yy23;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy61;
		default: goto yy23;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy63;
		default: goto yy23;
	}
yy32:
	++YYCURSOR;
#line 103 "implicit.re"
	{   return "int"; }
#line 350 "implicit.c"
yy33:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy34:
	switch (yych) {
		case 0x00: goto yy64;
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7': goto yy33;
		case '.': goto yy35;
		case '8':
		case '9': goto yy56;
		case ':': goto yy38;
		default: goto yy23;
	}
yy35:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy65;
		case ',': goto yy66;
		case '.': goto yy67;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy35;
		case 'E':
		case 'e': goto yy68;
		default: goto yy23;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7': goto yy69;
		case '8':
		case '9': goto yy70;
		default: goto yy34;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy70;
		default: goto yy57;
	}
yy38:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5': goto yy71;
		case '6':
		case '7':
		case '8':
		case '9': goto yy72;
		default: goto yy23;
	}
yy39:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy23;
	goto yy74;
yy40:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy23;
	goto yy76;
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy77;
		default: goto yy26;
	}
yy42:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy78;
	goto yy23;
yy43:
	++YYCURSOR;
#line 114 "implicit.re"
	{   return "default"; }
#line 473 "implicit.c"
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy79;
		default: goto yy23;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy80;
		default: goto yy23;
	}
yy46:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy81;
	goto yy23;
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy82;
		default: goto yy23;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy83;
		default: goto yy23;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'F': goto yy46;
		default: goto yy23;
	}
yy50:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy84;
	goto yy23;
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy46;
		default: goto yy23;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'U': goto yy85;
		default: goto yy23;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy86;
		default: goto yy23;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S': goto yy50;
		default: goto yy23;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy50;
		default: goto yy23;
	}
yy56:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy57:
	switch (yych) {
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy56;
		case '.': goto yy35;
		case ':': goto yy38;
		default: goto yy23;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N': goto yy87;
		case 'n': goto yy88;
		default: goto yy23;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy88;
		default: goto yy23;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'F': goto yy89;
		default: goto yy23;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy89;
		default: goto yy23;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'N': goto yy90;
		default: goto yy23;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy90;
		default: goto yy23;
	}
yy64:
	++YYCURSOR;
#line 100 "implicit.re"
	{   return "int#oct"; }
#line 604 "implicit.c"
yy65:
	++YYCURSOR;
#line 104 "implicit.re"
	{   return "float#fix"; }
#line 609 "implicit.c"
yy66:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy65;
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy66;
		default: goto yy23;
	}
yy67:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy67;
		case 'E':
		case 'e': goto yy68;
		default: goto yy23;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+':
		case '-': goto yy91;
		default: goto yy23;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7': goto yy92;
		case '8':
		case '9': goto yy93;
		default: goto yy34;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy93;
		default: goto yy57;
	}
yy71:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy94;
		case '.': goto yy95;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy72;
		case ':': goto yy38;
		default: goto yy23;
	}
yy72:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy94;
		case '.': goto yy95;
		case ':': goto yy38;
		default: goto yy23;
	}
yy73:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy74:
	switch (yych) {
		case 0x00: goto yy96;
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7': goto yy73;
		default: goto yy23;
	}
yy75:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy76:
	switch (yych) {
		case 0x00: goto yy97;
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy75;
		default: goto yy23;
	}
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy98;
		default: goto yy26;
	}
yy78:
	++YYCURSOR;
#line 115 "implicit.re"
	{   return "merge"; }
#line 785 "implicit.c"
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'S': goto yy99;
		default: goto yy23;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy100;
		default: goto yy23;
	}
yy81:
	++YYCURSOR;
#line 96 "implicit.re"
	{   return "bool#no"; }
#line 802 "implicit.c"
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy101;
		default: goto yy23;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy101;
		default: goto yy23;
	}
yy84:
	++YYCURSOR;
#line 95 "implicit.re"
	{   return "bool#yes"; }
#line 819 "implicit.c"
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E': goto yy50;
		default: goto yy23;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy50;
		default: goto yy23;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'F': goto yy102;
		default: goto yy23;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy102;
		default: goto yy23;
	}
yy89:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy103;
	goto yy23;
yy90:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy104;
	goto yy23;
yy91:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy23;
	goto yy106;
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy107;
		default: goto yy34;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy107;
		default: goto yy57;
	}
yy94:
	++YYCURSOR;
#line 102 "implicit.re"
	{   return "int#base60"; }
#line 872 "implicit.c"
yy95:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy108;
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy95;
		default: goto yy23;
	}
yy96:
	++YYCURSOR;
#line 101 "implicit.re"
	{   return "int#oct"; }
#line 896 "implicit.c"
yy97:
	++YYCURSOR;
#line 99 "implicit.re"
	{   return "int#hex"; }
#line 901 "implicit.c"
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy107;
		default: goto yy26;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'E': goto yy46;
		default: goto yy23;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy46;
		default: goto yy23;
	}
yy101:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy1;
	goto yy23;
yy102:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy109;
	goto yy23;
yy103:
	++YYCURSOR;
#line 107 "implicit.re"
	{   return "float#inf"; }
#line 932 "implicit.c"
yy104:
	++YYCURSOR;
#line 109 "implicit.re"
	{   return "float#nan"; }
#line 937 "implicit.c"
yy105:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy106:
	switch (yych) {
		case 0x00: goto yy110;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy105;
		default: goto yy23;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy111;
		default: goto yy23;
	}
yy108:
	++YYCURSOR;
#line 106 "implicit.re"
	{   return "float#base60"; }
#line 976 "implicit.c"
yy109:
	++YYCURSOR;
#line 108 "implicit.re"
	{   return "float#neginf"; }
#line 981 "implicit.c"
yy110:
	++YYCURSOR;
#line 105 "implicit.re"
	{   return "float#exp"; }
#line 986 "implicit.c"
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy112;
		default: goto yy23;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy113;
		default: goto yy23;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy114;
		default: goto yy23;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy115;
		default: goto yy23;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy116;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy23;
		case 'T':
		case 't': goto yy119;
		default: goto yy118;
	}
yy116:
	++YYCURSOR;
#line 110 "implicit.re"
	{   return "timestamp#ymd"; }
#line 1060 "implicit.c"
yy117:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
	yych = *YYCURSOR;
yy118:
	switch (yych) {
		case '\t':
		case ' ': goto yy117;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy120;
		default: goto yy23;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy121;
		default: goto yy23;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy122;
		default: goto yy23;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy123;
		default: goto yy23;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
		case ':': goto yy124;
		default: goto yy23;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
		case ':': goto yy125;
		default: goto yy23;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy126;
		default: goto yy23;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy127;
		default: goto yy23;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy128;
		default: goto yy23;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy129;
		default: goto yy23;
	}
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
		case ':': goto yy130;
		default: goto yy23;
	}
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
		case ':': goto yy131;
		default: goto yy23;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy132;
		default: goto yy23;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy133;
		default: goto yy23;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy134;
		default: goto yy23;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy135;
		default: goto yy23;
	}
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy137;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy23;
		default: goto yy138;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy140;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy23;
		default: goto yy141;
	}
yy136:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
	switch (yych) {
		case '\t':
		case ' ': goto yy136;
		case '+':
		case '-': goto yy143;
		case 'Z': goto yy144;
		default: goto yy23;
	}
yy137:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy138:
	switch (yych) {
		case '\t':
		case ' ': goto yy136;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy137;
		default: goto yy23;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy145;
		default: goto yy23;
	}
yy140:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
yy141:
	switch (yych) {
		case '+':
		case '-': goto yy139;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy140;
		case 'Z': goto yy142;
		default: goto yy23;
	}
yy142:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy146;
	goto yy23;
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy147;
		default: goto yy23;
	}
yy144:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy148;
	goto yy23;
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy149;
		default: goto yy23;
	}
yy146:
	++YYCURSOR;
#line 111 "implicit.re"
	{   return "timestamp#iso8601"; }
#line 1412 "implicit.c"
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy150;
		default: goto yy23;
	}
yy148:
	++YYCURSOR;
#line 112 "implicit.re"
	{   return "timestamp#spaced"; }
#line 1432 "implicit.c"
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy146;
		case ':': goto yy151;
		default: goto yy23;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00: goto yy148;
		case ':': goto yy152;
		default: goto yy23;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy153;
		default: goto yy23;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy154;
		default: goto yy23;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy142;
		default: goto yy23;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy144;
		default: goto yy23;
	}
}
#line 118 "implicit.re"


}

/* Remove ending fragment and compare types */
int
syck_tagcmp( const char *tag1, const char *tag2 )
{
    if ( tag1 == tag2 ) return 1;
    if ( tag1 == NULL || tag2 == NULL ) return 0;
    else {
        int i;
        char *othorpe;
        char *tmp1 = syck_strndup( tag1, strlen( tag1 ) );
        char *tmp2 = syck_strndup( tag2, strlen( tag2 ) );
        othorpe = strstr( tmp1, "#" );
        if ( othorpe != NULL ) {
            othorpe[0] = '\0';
        }
        othorpe = strstr( tmp2, "#" );
        if ( othorpe != NULL ) {
            othorpe[0] = '\0';
        }
        i = strcmp( tmp1, tmp2 );
        S_FREE( tmp1 ); S_FREE( tmp2 );
        return i;
    }
}

char *
syck_type_id_to_uri( char *type_id )
{
    char *cursor, *limit, *marker = NULL;

    cursor = type_id;
    limit = type_id + strlen( type_id );


#line 1547 "implicit.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 21) YYFILL(21);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy156;
		case '!': goto yy159;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'y':
		case 'z': goto yy161;
		case 't': goto yy162;
		case 'x': goto yy163;
		default: goto yy157;
	}
yy156:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy160;
	} else {
		goto yy158;
	}
yy157:
	++YYCURSOR;
yy158:
#line 211 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, type_id, strlen( type_id ) ); }
#line 1633 "implicit.c"
yy159:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '!': goto yy164;
		case 'b': goto yy165;
		case 'f': goto yy166;
		case 'i': goto yy167;
		case 'm': goto yy168;
		case 'n': goto yy169;
		case 's': goto yy170;
		default: goto yy160;
	}
yy160:
#line 185 "implicit.re"
	{   return syck_xprivate( type_id + 1, strlen( type_id ) - 1 ); }
#line 1650 "implicit.c"
yy161:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy177;
		default: goto yy158;
	}
yy162:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy177;
		case 'a': goto yy178;
		default: goto yy158;
	}
yy163:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case ',':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy177;
		case '-': goto yy179;
		default: goto yy158;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'b': goto yy180;
		case 'f': goto yy181;
		case 'i': goto yy182;
		case 'm': goto yy183;
		case 'n': goto yy184;
		case 's': goto yy185;
		default: goto yy156;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy186;
		default: goto yy156;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy187;
		default: goto yy156;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy188;
		default: goto yy156;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy189;
		default: goto yy156;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy190;
		default: goto yy156;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy191;
		case 't': goto yy192;
		default: goto yy156;
	}
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy193;
		default: goto yy156;
	}
yy172:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy173:
	switch (yych) {
		case '-': goto yy172;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy176;
		default: goto yy156;
	}
yy174:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy176;
		default: goto yy156;
	}
yy175:
	++YYCURSOR;
#line 187 "implicit.re"
	{   char *domain = S_ALLOC_N( char, ( YYCURSOR - type_id ) + 15 );
                    char *uri;

                    domain[0] = '\0';
                    strncat( domain, type_id, ( YYCURSOR - type_id ) - 1 );
                    strcat( domain, "." );
                    strcat( domain, YAML_DOMAIN );
                    uri = syck_taguri( domain, YYCURSOR, YYLIMIT - YYCURSOR );

                    S_FREE( domain );
                    return uri;
                }
#line 2090 "implicit.c"
yy176:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 12) YYFILL(12);
	yych = *YYCURSOR;
yy177:
	switch (yych) {
		case ',': goto yy171;
		case '-': goto yy172;
		case '.': goto yy174;
		case '/': goto yy175;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy176;
		default: goto yy156;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy171;
		case '.': goto yy174;
		case '/': goto yy175;
		case 'g': goto yy194;
		default: goto yy173;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'p': goto yy195;
		default: goto yy173;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy196;
		default: goto yy156;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy197;
		default: goto yy156;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy198;
		default: goto yy156;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy199;
		default: goto yy156;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy200;
		default: goto yy156;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy201;
		case 't': goto yy202;
		default: goto yy156;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy203;
		default: goto yy156;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy204;
		default: goto yy156;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy205;
		default: goto yy156;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'p': goto yy206;
		default: goto yy156;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy207;
		default: goto yy156;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'q': goto yy208;
		default: goto yy156;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy209;
		default: goto yy156;
	}
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy210;
		default: goto yy156;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy171;
		case '.': goto yy174;
		case '/': goto yy175;
		case ':': goto yy211;
		default: goto yy173;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy171;
		case '.': goto yy174;
		case '/': goto yy175;
		case 'r': goto yy212;
		default: goto yy173;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy213;
		default: goto yy156;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy214;
		default: goto yy156;
	}
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy215;
		default: goto yy156;
	}
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'p': goto yy216;
		default: goto yy156;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy217;
		default: goto yy156;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'q': goto yy218;
		default: goto yy156;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy219;
		default: goto yy156;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy220;
		default: goto yy156;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy221;
		default: goto yy156;
	}
yy205:
	++YYCURSOR;
#line 170 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "int", 5 ); }
#line 2351 "implicit.c"
yy206:
	++YYCURSOR;
#line 172 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "map", 5 ); }
#line 2356 "implicit.c"
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy222;
		default: goto yy156;
	}
yy208:
	++YYCURSOR;
#line 171 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "seq", 5 ); }
#line 2367 "implicit.c"
yy209:
	++YYCURSOR;
#line 169 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "str", 5 ); }
#line 2372 "implicit.c"
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy223;
		default: goto yy156;
	}
yy211:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy224;
		default: goto yy156;
	}
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy171;
		case '.': goto yy174;
		case '/': goto yy175;
		case 'i': goto yy225;
		default: goto yy173;
	}
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy226;
		default: goto yy156;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy227;
		default: goto yy156;
	}
yy215:
	++YYCURSOR;
#line 178 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "int", 5 ); }
#line 2483 "implicit.c"
yy216:
	++YYCURSOR;
#line 180 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "map", 5 ); }
#line 2488 "implicit.c"
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy228;
		default: goto yy156;
	}
yy218:
	++YYCURSOR;
#line 179 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "seq", 5 ); }
#line 2499 "implicit.c"
yy219:
	++YYCURSOR;
#line 177 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "str", 5 ); }
#line 2504 "implicit.c"
yy220:
	++YYCURSOR;
#line 173 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "bool", 6 ); }
#line 2509 "implicit.c"
yy221:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy229;
		default: goto yy156;
	}
yy222:
	++YYCURSOR;
#line 174 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "null", 6 ); }
#line 2520 "implicit.c"
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy230;
		default: goto yy156;
	}
yy224:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 12) YYFILL(12);
	yych = *YYCURSOR;
	switch (yych) {
		case ',': goto yy231;
		case '-': goto yy232;
		case '.': goto yy211;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy224;
		default: goto yy156;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy171;
		case '.': goto yy174;
		case '/': goto yy175;
		case 'v': goto yy233;
		default: goto yy173;
	}
yy226:
	++YYCURSOR;
#line 181 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "bool", 6 ); }
#line 2622 "implicit.c"
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy234;
		default: goto yy156;
	}
yy228:
	++YYCURSOR;
#line 182 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "null", 6 ); }
#line 2633 "implicit.c"
yy229:
	++YYCURSOR;
#line 175 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "float", 7 ); }
#line 2638 "implicit.c"
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy235;
		case '/': goto yy236;
		default: goto yy156;
	}
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy237;
		default: goto yy156;
	}
yy232:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '-': goto yy232;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy224;
		default: goto yy156;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy171;
		case '.': goto yy174;
		case '/': goto yy175;
		case 'a': goto yy238;
		default: goto yy173;
	}
yy234:
	++YYCURSOR;
#line 183 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "float", 7 ); }
#line 2745 "implicit.c"
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy239;
		default: goto yy156;
	}
yy236:
	++YYCURSOR;
#line 200 "implicit.re"
	{   char *domain = S_ALLOC_N( char, YYCURSOR - type_id );
                               char *uri;

                               domain[0] = '\0';
                               strncat( domain, type_id, ( YYCURSOR - type_id ) - 1 );
                               uri = syck_taguri( domain, YYCURSOR, YYLIMIT - YYCURSOR );

                               S_FREE( domain );
                               return uri;
                            }
#line 2774 "implicit.c"
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy240;
		default: goto yy156;
	}
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy171;
		case '.': goto yy174;
		case '/': goto yy175;
		case 't': goto yy241;
		default: goto yy173;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy242;
		default: goto yy156;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy243;
		default: goto yy156;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy171;
		case '.': goto yy174;
		case '/': goto yy175;
		case 'e': goto yy244;
		default: goto yy173;
	}
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy245;
		case '/': goto yy236;
		default: goto yy156;
	}
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy246;
		default: goto yy156;
	}
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
		case ',': goto yy171;
		case '.': goto yy174;
		case '/': goto yy175;
		case ':': goto yy247;
		default: goto yy173;
	}
yy245:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy248;
		default: goto yy156;
	}
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy249;
		case ':': goto yy250;
		default: goto yy156;
	}
yy247:
	++YYCURSOR;
#line 167 "implicit.re"
	{   return syck_strndup( type_id, strlen( type_id ) ); }
#line 2895 "implicit.c"
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy251;
		default: goto yy156;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy252;
		default: goto yy156;
	}
yy250:
	++YYCURSOR;
#line 165 "implicit.re"
	{   return syck_strndup( type_id, strlen( type_id ) ); }
#line 2930 "implicit.c"
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
		case '/': goto yy236;
		default: goto yy156;
	}
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy253;
		default: goto yy156;
	}
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy254;
		case ':': goto yy250;
		default: goto yy156;
	}
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy255;
		default: goto yy156;
	}
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy256;
		default: goto yy156;
	}
yy256:
	yych = *++YYCURSOR;
	switch (yych) {
		case ':': goto yy250;
		default: goto yy156;
	}
}
#line 213 "implicit.re"


}
