/* ex: set ro ft=c: -*- mode: c; buffer-read-only: t -*- *//* Generated by re2c 3.1 */
#line 1 "implicit.re"
/*
 * implicit.re
 *
 * $Author: why $
 * $Date: 2005/11/13 23:43:56 $
 *
 * Copyright (C) 2003 why the lucky stiff
 * Copyright (C) 2026 Reini Urban
 */

#include "syck.h"
#include <string.h>
#include <assert.h>

#if !defined(YYCSZ) || YYCSZ == 8
#define YYCSZ 8
#define YYCTYPE     unsigned char
#elif YYCSZ == 16
#include <stdint.h>
#define YYCTYPE     uint16_t
#elif YYCSZ == 32
#include <stdint.h>
#define YYCTYPE     uint32_t
#endif

#define YYCURSOR    cursor
#define YYMARKER    marker
#define YYLIMIT     limit
#define YYFILL(n)   {}

void try_tag_implicit8( SyckNode *n, int taguri );
void try_tag_implicit16( SyckNode *n, int taguri );
void try_tag_implicit32( SyckNode *n, int taguri );

#if YYCSZ == 8
void
try_tag_implicit(const SyckParser *p, SyckNode *n )
{
    switch(p->input_type) {
    case syck_yaml_utf8:
        return try_tag_implicit8(n, p->taguri_expansion);
    case syck_yaml_utf16:
        return try_tag_implicit16(n, p->taguri_expansion);
    case syck_yaml_utf32:
        return try_tag_implicit32(n, p->taguri_expansion);
    case syck_bytecode_utf8:
    case syck_yaml_utf32be:
    case syck_yaml_utf16be:
    default:
        /* unsupported */
        assert(0);
        return;
    }
}
#endif

void
#if YYCSZ == 8
try_tag_implicit8( SyckNode *n, int taguri )
#elif YYCSZ == 16
try_tag_implicit16( SyckNode *n, int taguri )
#elif YYCSZ == 32
try_tag_implicit32( SyckNode *n, int taguri )
#endif
{
    const char *tid = "";
    switch ( n->kind )
    {
        case syck_str_kind:
#if YYCSZ == 8
            tid = syck_match_implicit8( (uint8_t*)n->data.str->ptr, n->data.str->len );
#elif YYCSZ == 16
            tid = syck_match_implicit16( (uint16_t*)n->data.str->ptr, n->data.str->len );
#elif YYCSZ == 32
            tid = syck_match_implicit32( (uint32_t*)n->data.str->ptr, n->data.str->len );
#endif
            break;

        case syck_seq_kind:
            tid = "seq";
            break;

        case syck_map_kind:
            tid = "map";
            break;

        default:
            break;
    }
    if ( n->type_id != NULL ) {
       S_FREE( n->type_id );
    }
    if ( taguri == 1 )
    {
        n->type_id = syck_taguri( YAML_DOMAIN, tid, strlen( tid ) );
    } else {
        n->type_id = syck_strndup( tid, strlen( tid ) );
    }
}

const char*
#if YYCSZ == 8
syck_match_implicit8
#elif YYCSZ == 16
syck_match_implicit16
#elif YYCSZ == 32
syck_match_implicit32
#endif
                      ( const YYCTYPE *str, size_t len )
{
    YYCTYPE *marker;
    YYCTYPE *cursor = (YYCTYPE *)str;
    const YYCTYPE *limit = str + len;


#line 119 "implicit.c"
{
	YYCTYPE yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,  76,   0,  32,   0, 
		124, 124, 124, 124, 124, 124, 124, 124, 
		116, 116,   0,   0,   0,   0,   0,   0, 
		  0,  64,  64,  64,  64,  64,  64,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,  64,  64,  64,  64,  64,  64,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((YYLIMIT - YYCURSOR) < 26) YYFILL(26);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy2,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy5,  &&yy3,  &&yy6,  &&yy7,  &&yy3,
			&&yy8,  &&yy9,  &&yy9,  &&yy9,  &&yy9,  &&yy9,  &&yy9,  &&yy9,
			&&yy9,  &&yy9,  &&yy3,  &&yy3,  &&yy10, &&yy11, &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy12, &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy13, &&yy14,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy15, &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy16, &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy17, &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy18, &&yy19,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy20, &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy21, &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy22, &&yy3,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy23, &&yy23, &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1
		};
		goto *yytarget[yych];
	}
yy1:
	YYCURSOR = YYMARKER;
	goto yy4;
yy2:
	++YYCURSOR;
#line 149 "implicit.re"
	{   return "null"; }
#line 202 "implicit.c"
yy3:
	++YYCURSOR;
yy4:
#line 168 "implicit.re"
	{   return "str"; }
#line 208 "implicit.c"
yy5:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= '/') {
		if (yych == '.') goto yy24;
		goto yy4;
	} else {
		if (yych <= '0') goto yy25;
		if (yych <= '9') goto yy26;
		goto yy4;
	}
yy6:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= '/') {
		if (yych == '.') goto yy28;
		goto yy4;
	} else {
		if (yych <= '0') goto yy25;
		if (yych <= '9') goto yy26;
		goto yy4;
	}
yy7:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy29, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy30, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy31, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy32, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4
		};
		goto *yytarget[yych];
	}
yy8:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy33, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy34, &&yy4,  &&yy36, &&yy4,
			&&yy37, &&yy37, &&yy37, &&yy37, &&yy37, &&yy37, &&yy37, &&yy37,
			&&yy38, &&yy38, &&yy39, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy40, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4
		};
		goto *yytarget[yych];
	}
yy9:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy33, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy26, &&yy4,  &&yy36, &&yy4,
			&&yy41, &&yy41, &&yy41, &&yy41, &&yy41, &&yy41, &&yy41, &&yy41,
			&&yy41, &&yy41, &&yy39, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4
		};
		goto *yytarget[yych];
	}
yy10:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == '<') goto yy42;
	goto yy4;
yy11:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy43;
	goto yy4;
yy12:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'A') goto yy44;
	if (yych == 'a') goto yy45;
	goto yy4;
yy13:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy46,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy47, &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy46,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy48, &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4
		};
		goto *yytarget[yych];
	}
yy14:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy49, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy50, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy51, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy50, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4
		};
		goto *yytarget[yych];
	}
yy15:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'R') goto yy52;
	if (yych == 'r') goto yy53;
	goto yy4;
yy16:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'E') goto yy54;
	if (yych == 'e') goto yy55;
	goto yy4;
yy17:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'a') goto yy45;
	goto yy4;
yy18:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'o') goto yy46;
	if (yych == 'u') goto yy48;
	goto yy4;
yy19:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'f') goto yy51;
	if (yych == 'n') goto yy50;
	goto yy4;
yy20:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'r') goto yy53;
	goto yy4;
yy21:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'e') goto yy55;
	goto yy4;
yy22:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy2;
	goto yy4;
yy23:
	yych = *++YYCURSOR;
	if (yych <= 0x7F) goto yy1;
	if (yych <= 0xBF) goto yy3;
	goto yy1;
yy24:
	yych = *++YYCURSOR;
	if (yych == 'I') goto yy29;
	if (yych == 'i') goto yy31;
	goto yy1;
yy25:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy33;
	if (yych == 'x') goto yy40;
	goto yy35;
yy26:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy27:
	if (yybm[0+yych] & 4) {
		goto yy26;
	}
	if (yych <= '.') {
		if (yych <= 0x00) goto yy33;
		if (yych <= '-') goto yy1;
		goto yy36;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= ':') goto yy39;
		goto yy1;
	}
yy28:
	yych = *++YYCURSOR;
	if (yych == 'I') goto yy58;
	if (yych == 'i') goto yy59;
	goto yy1;
yy29:
	yych = *++YYCURSOR;
	if (yych == 'N') goto yy60;
	if (yych == 'n') goto yy61;
	goto yy1;
yy30:
	yych = *++YYCURSOR;
	if (yych == 'A') goto yy62;
	if (yych == 'a') goto yy62;
	goto yy1;
yy31:
	yych = *++YYCURSOR;
	if (yych == 'n') goto yy61;
	goto yy1;
yy32:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy63;
	goto yy1;
yy33:
	++YYCURSOR;
#line 155 "implicit.re"
	{   return "int"; }
#line 532 "implicit.c"
yy34:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy35:
	if (yybm[0+yych] & 8) {
		goto yy34;
	}
	if (yych <= '.') {
		if (yych <= 0x00) goto yy64;
		if (yych <= '-') goto yy1;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy56;
		if (yych <= ':') goto yy39;
		goto yy1;
	}
yy36:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy65, &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy66, &&yy1,  &&yy67, &&yy1,
			&&yy36, &&yy36, &&yy36, &&yy36, &&yy36, &&yy36, &&yy36, &&yy36,
			&&yy36, &&yy36, &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy68, &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy68, &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1
		};
		goto *yytarget[yych];
	}
yy37:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy35;
	if (yych <= '7') goto yy69;
	if (yych <= '9') goto yy70;
	goto yy35;
yy38:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy57;
	if (yych <= '9') goto yy70;
	goto yy57;
yy39:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '5') goto yy71;
	if (yych <= '9') goto yy72;
	goto yy1;
yy40:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy1;
	goto yy74;
yy41:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy27;
	if (yych <= '9') goto yy75;
	goto yy27;
yy42:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy76;
	goto yy1;
yy43:
	++YYCURSOR;
#line 166 "implicit.re"
	{   return "default"; }
#line 627 "implicit.c"
yy44:
	yych = *++YYCURSOR;
	if (yych == 'L') goto yy77;
	goto yy1;
yy45:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy78;
	goto yy1;
yy46:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy79;
	goto yy1;
yy47:
	yych = *++YYCURSOR;
	if (yych == 'L') goto yy80;
	goto yy1;
yy48:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy81;
	goto yy1;
yy49:
	yych = *++YYCURSOR;
	if (yych == 'F') goto yy46;
	goto yy1;
yy50:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy82;
	goto yy1;
yy51:
	yych = *++YYCURSOR;
	if (yych == 'f') goto yy46;
	goto yy1;
yy52:
	yych = *++YYCURSOR;
	if (yych == 'U') goto yy83;
	goto yy1;
yy53:
	yych = *++YYCURSOR;
	if (yych == 'u') goto yy84;
	goto yy1;
yy54:
	yych = *++YYCURSOR;
	if (yych == 'S') goto yy50;
	goto yy1;
yy55:
	yych = *++YYCURSOR;
	if (yych == 's') goto yy50;
	goto yy1;
yy56:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy57:
	if (yych <= '.') {
		if (yych == ',') goto yy56;
		if (yych <= '-') goto yy1;
		goto yy36;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy56;
		if (yych <= ':') goto yy39;
		goto yy1;
	}
yy58:
	yych = *++YYCURSOR;
	if (yych == 'N') goto yy85;
	if (yych == 'n') goto yy86;
	goto yy1;
yy59:
	yych = *++YYCURSOR;
	if (yych == 'n') goto yy86;
	goto yy1;
yy60:
	yych = *++YYCURSOR;
	if (yych == 'F') goto yy87;
	goto yy1;
yy61:
	yych = *++YYCURSOR;
	if (yych == 'f') goto yy87;
	goto yy1;
yy62:
	yych = *++YYCURSOR;
	if (yych == 'N') goto yy88;
	goto yy1;
yy63:
	yych = *++YYCURSOR;
	if (yych == 'n') goto yy88;
	goto yy1;
yy64:
	++YYCURSOR;
#line 153 "implicit.re"
	{   return "int#oct"; }
#line 720 "implicit.c"
yy65:
	++YYCURSOR;
#line 156 "implicit.re"
	{   return "float#fix"; }
#line 725 "implicit.c"
yy66:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= ',') {
		if (yych <= 0x00) goto yy65;
		if (yych <= '+') goto yy1;
		goto yy66;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy66;
		goto yy1;
	}
yy67:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 32) {
		goto yy67;
	}
	if (yych == 'E') goto yy68;
	if (yych != 'e') goto yy1;
yy68:
	yych = *++YYCURSOR;
	if (yych == '+') goto yy89;
	if (yych == '-') goto yy89;
	goto yy1;
yy69:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy35;
	if (yych <= '7') goto yy90;
	if (yych <= '9') goto yy91;
	goto yy35;
yy70:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy57;
	if (yych <= '9') goto yy91;
	goto yy57;
yy71:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= '.') {
		if (yych <= 0x00) goto yy92;
		if (yych <= '-') goto yy1;
		goto yy93;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy72;
		if (yych <= ':') goto yy39;
		goto yy1;
	}
yy72:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= '.') {
		if (yych <= 0x00) goto yy92;
		if (yych <= '-') goto yy1;
		goto yy93;
	} else {
		if (yych == ':') goto yy39;
		goto yy1;
	}
yy73:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy74:
	if (yybm[0+yych] & 64) {
		goto yy73;
	}
	if (yych <= 0x00) goto yy94;
	goto yy1;
yy75:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy27;
	if (yych <= '9') goto yy95;
	goto yy27;
yy76:
	++YYCURSOR;
#line 167 "implicit.re"
	{   return "merge"; }
#line 809 "implicit.c"
yy77:
	yych = *++YYCURSOR;
	if (yych == 'S') goto yy96;
	goto yy1;
yy78:
	yych = *++YYCURSOR;
	if (yych == 's') goto yy97;
	goto yy1;
yy79:
	++YYCURSOR;
#line 151 "implicit.re"
	{   return "bool#no"; }
#line 822 "implicit.c"
yy80:
	yych = *++YYCURSOR;
	if (yych == 'L') goto yy98;
	goto yy1;
yy81:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy98;
	goto yy1;
yy82:
	++YYCURSOR;
#line 150 "implicit.re"
	{   return "bool#yes"; }
#line 835 "implicit.c"
yy83:
	yych = *++YYCURSOR;
	if (yych == 'E') goto yy50;
	goto yy1;
yy84:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy50;
	goto yy1;
yy85:
	yych = *++YYCURSOR;
	if (yych == 'F') goto yy99;
	goto yy1;
yy86:
	yych = *++YYCURSOR;
	if (yych == 'f') goto yy99;
	goto yy1;
yy87:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy100;
	goto yy1;
yy88:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy101;
	goto yy1;
yy89:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy1;
	goto yy103;
yy90:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy104;
	goto yy35;
yy91:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy104;
	goto yy57;
yy92:
	++YYCURSOR;
#line 154 "implicit.re"
	{   return "int#base60"; }
#line 876 "implicit.c"
yy93:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= ',') {
		if (yych <= 0x00) goto yy105;
		if (yych <= '+') goto yy1;
		goto yy93;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy93;
		goto yy1;
	}
yy94:
	++YYCURSOR;
#line 152 "implicit.re"
	{   return "int#hex"; }
#line 894 "implicit.c"
yy95:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy104;
	goto yy27;
yy96:
	yych = *++YYCURSOR;
	if (yych == 'E') goto yy46;
	goto yy1;
yy97:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy46;
	goto yy1;
yy98:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy2;
	goto yy1;
yy99:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy106;
	goto yy1;
yy100:
	++YYCURSOR;
#line 159 "implicit.re"
	{   return "float#inf"; }
#line 919 "implicit.c"
yy101:
	++YYCURSOR;
#line 161 "implicit.re"
	{   return "float#nan"; }
#line 924 "implicit.c"
yy102:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy103:
	if (yych <= 0x00) goto yy107;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy102;
	goto yy1;
yy104:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy108;
	goto yy1;
yy105:
	++YYCURSOR;
#line 158 "implicit.re"
	{   return "float#base60"; }
#line 943 "implicit.c"
yy106:
	++YYCURSOR;
#line 160 "implicit.re"
	{   return "float#neginf"; }
#line 948 "implicit.c"
yy107:
	++YYCURSOR;
#line 157 "implicit.re"
	{   return "float#exp"; }
#line 953 "implicit.c"
yy108:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych >= ':') goto yy1;
	yych = *++YYCURSOR;
	if (yych != '-') goto yy1;
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych >= ':') goto yy1;
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych >= ':') goto yy1;
	yych = *++YYCURSOR;
	if (yych <= 'S') {
		if (yych <= 0x00) goto yy109;
		if (yych <= '/') goto yy111;
		if (yych <= '9') goto yy1;
		goto yy111;
	} else {
		if (yych <= 'T') goto yy112;
		if (yych == 't') goto yy112;
		goto yy111;
	}
yy109:
	++YYCURSOR;
#line 162 "implicit.re"
	{   return "timestamp#ymd"; }
#line 981 "implicit.c"
yy110:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
	yych = *YYCURSOR;
yy111:
	if (yybm[0+yych] & 128) {
		goto yy110;
	}
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy113;
	goto yy1;
yy112:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy114;
	goto yy1;
yy113:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy115;
	goto yy1;
yy114:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy116;
	goto yy1;
yy115:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy117;
	goto yy1;
yy116:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy118;
	goto yy1;
yy117:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy119;
	goto yy1;
yy118:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy120;
	goto yy1;
yy119:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy121;
	goto yy1;
yy120:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy122;
	goto yy1;
yy121:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy123;
	goto yy1;
yy122:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy124;
	goto yy1;
yy123:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy125;
	goto yy1;
yy124:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy126;
	goto yy1;
yy125:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy127;
	goto yy1;
yy126:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy128;
	goto yy1;
yy127:
	yych = *++YYCURSOR;
	if (yych == '.') goto yy130;
	if (yych <= '/') goto yy131;
	if (yych <= '9') goto yy1;
	goto yy131;
yy128:
	yych = *++YYCURSOR;
	if (yych == '.') goto yy133;
	if (yych <= '/') goto yy134;
	if (yych <= '9') goto yy1;
	goto yy134;
yy129:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy129, &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy129, &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy136, &&yy1,   &&yy136, &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy137, &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1
		};
		goto *yytarget[yych];
	}
yy130:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy131:
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy129;
		goto yy1;
	} else {
		if (yych <= ' ') goto yy129;
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy130;
		goto yy1;
	}
yy132:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy138;
	goto yy1;
yy133:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
yy134:
	{
		static void *yytarget[256] = {
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy132, &&yy1,   &&yy132, &&yy1,   &&yy1,
			&&yy133, &&yy133, &&yy133, &&yy133, &&yy133, &&yy133, &&yy133, &&yy133,
			&&yy133, &&yy133, &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy135, &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1
		};
		goto *yytarget[yych];
	}
yy135:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy139;
	goto yy1;
yy136:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy140;
	goto yy1;
yy137:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy141;
	goto yy1;
yy138:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy142;
	goto yy1;
yy139:
	++YYCURSOR;
#line 163 "implicit.re"
	{   return "timestamp#iso8601"; }
#line 1200 "implicit.c"
yy140:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy143;
	goto yy1;
yy141:
	++YYCURSOR;
#line 164 "implicit.re"
	{   return "timestamp#spaced"; }
#line 1210 "implicit.c"
yy142:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy139;
	if (yych == ':') goto yy144;
	goto yy1;
yy143:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy141;
	if (yych == ':') goto yy145;
	goto yy1;
yy144:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy146;
	goto yy1;
yy145:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy147;
	goto yy1;
yy146:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy135;
	goto yy1;
yy147:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy137;
	goto yy1;
}
#line 170 "implicit.re"


}

#if YYCSZ == 8
/* Remove ending fragment and compare types */
int
syck_tagcmp( const char *tag1, const char *tag2 )
{
    if ( tag1 == tag2 ) return 1;
    if ( tag1 == NULL || tag2 == NULL ) return 0;
    else {
        int i;
        char *othorpe;
        char *tmp1 = syck_strndup( tag1, strlen( tag1 ) );
        char *tmp2 = syck_strndup( tag2, strlen( tag2 ) );
        othorpe = strstr( tmp1, "#" );
		if ( othorpe != NULL ) {
            othorpe[0] = '\0';
        }
        othorpe = strstr( tmp2, "#" );
		if ( othorpe != NULL ) {
            othorpe[0] = '\0';
        }
        i = strcmp( tmp1, tmp2 );
        S_FREE( tmp1 ); S_FREE( tmp2 );
        return i;
    }
}

char *
syck_type_id_to_uri( char *type_id )
{
    char *cursor, *limit, *marker = NULL;

    cursor = type_id;
    limit = type_id + strlen( type_id );


#line 1282 "implicit.c"
{
	YYCTYPE yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,  64,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0, 128, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((YYLIMIT - YYCURSOR) < 21) YYFILL(21);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy149, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150,
			&&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150,
			&&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150,
			&&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150,
			&&yy150, &&yy152, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150,
			&&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150,
			&&yy150, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy150, &&yy150, &&yy150, &&yy150, &&yy153,
			&&yy150, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy154, &&yy153, &&yy153, &&yy153,
			&&yy155, &&yy153, &&yy153, &&yy150, &&yy150, &&yy150, &&yy150, &&yy150,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy156, &&yy156, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149
		};
		goto *yytarget[yych];
	}
yy149:
	YYCURSOR = YYMARKER;
	goto yy151;
yy150:
	++YYCURSOR;
yy151:
#line 248 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, type_id, strlen( type_id ) ); }
#line 1366 "implicit.c"
yy152:
	++YYCURSOR;
#line 222 "implicit.re"
	{   return syck_xprivate( type_id + 1, strlen( type_id ) - 1 ); }
#line 1371 "implicit.c"
yy153:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy151, &&yy151, &&yy151, &&yy151, &&yy163,
			&&yy151, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151
		};
		goto *yytarget[yych];
	}
yy154:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy151, &&yy151, &&yy151, &&yy151, &&yy163,
			&&yy151, &&yy164, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151
		};
		goto *yytarget[yych];
	}
yy155:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy163, &&yy165, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy151, &&yy151, &&yy151, &&yy151, &&yy163,
			&&yy151, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163, &&yy163,
			&&yy163, &&yy163, &&yy163, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151,
			&&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151, &&yy151
		};
		goto *yytarget[yych];
	}
yy156:
	yych = *++YYCURSOR;
	if (yych <= 0x7F) goto yy149;
	if (yych <= 0xBF) goto yy150;
	goto yy149;
yy157:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy166;
	goto yy149;
yy158:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy159:
	if (yybm[0+yych] & 64) {
		goto yy158;
	}
	if (yych <= 'Z') {
		if (yych <= '/') goto yy149;
		if (yych <= '9') goto yy162;
		if (yych <= '@') goto yy149;
		goto yy162;
	} else {
		if (yych <= '_') {
			if (yych <= '^') goto yy149;
			goto yy162;
		} else {
			if (yych <= '`') goto yy149;
			if (yych <= 'z') goto yy162;
			goto yy149;
		}
	}
yy160:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy162;
	}
	goto yy149;
yy161:
	++YYCURSOR;
#line 224 "implicit.re"
	{   char *domain = S_ALLOC_N( char, ( YYCURSOR - type_id ) + 15 );
                    char *uri;

                    domain[0] = '\0';
                    strncat( domain, type_id, ( YYCURSOR - type_id ) - 1 );
                    strcat( domain, "." );
                    strcat( domain, YAML_DOMAIN );
                    uri = syck_taguri( domain, YYCURSOR, YYLIMIT - YYCURSOR );

                    S_FREE( domain );
                    return uri;
                }
#line 1545 "implicit.c"
yy162:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 12) YYFILL(12);
	yych = *YYCURSOR;
yy163:
	if (yybm[0+yych] & 64) {
		goto yy158;
	}
	if (yych <= '@') {
		if (yych <= '.') {
			if (yych <= '+') goto yy149;
			if (yych <= ',') goto yy157;
			goto yy160;
		} else {
			if (yych <= '/') goto yy161;
			if (yych <= '9') goto yy162;
			goto yy149;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy162;
			if (yych <= '^') goto yy149;
			goto yy162;
		} else {
			if (yych <= '`') goto yy149;
			if (yych <= 'z') goto yy162;
			goto yy149;
		}
	}
yy164:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy157;
		if (yych <= '-') goto yy159;
		goto yy160;
	} else {
		if (yych <= '/') goto yy161;
		if (yych == 'g') goto yy167;
		goto yy159;
	}
yy165:
	yych = *++YYCURSOR;
	if (yych == 'p') goto yy168;
	goto yy159;
yy166:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy169;
	goto yy149;
yy167:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy157;
		if (yych <= '-') goto yy159;
		goto yy160;
	} else {
		if (yych <= '/') goto yy161;
		if (yych == ':') goto yy170;
		goto yy159;
	}
yy168:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy157;
		if (yych <= '-') goto yy159;
		goto yy160;
	} else {
		if (yych <= '/') goto yy161;
		if (yych == 'r') goto yy171;
		goto yy159;
	}
yy169:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy172;
	goto yy149;
yy170:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy149, &&yy149, &&yy149, &&yy149, &&yy173,
			&&yy149, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149
		};
		goto *yytarget[yych];
	}
yy171:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy157;
		if (yych <= '-') goto yy159;
		goto yy160;
	} else {
		if (yych <= '/') goto yy161;
		if (yych == 'i') goto yy174;
		goto yy159;
	}
yy172:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy175;
	goto yy149;
yy173:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 12) YYFILL(12);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy176, &&yy177, &&yy170, &&yy149,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy149, &&yy149, &&yy149, &&yy149, &&yy173,
			&&yy149, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149
		};
		goto *yytarget[yych];
	}
yy174:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy157;
		if (yych <= '-') goto yy159;
		goto yy160;
	} else {
		if (yych <= '/') goto yy161;
		if (yych == 'v') goto yy178;
		goto yy159;
	}
yy175:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy179;
	if (yych == '/') goto yy180;
	goto yy149;
yy176:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy181;
	goto yy149;
yy177:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy177, &&yy149, &&yy149,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy149, &&yy149, &&yy149, &&yy149, &&yy173,
			&&yy149, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173, &&yy173,
			&&yy173, &&yy173, &&yy173, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149,
			&&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149, &&yy149
		};
		goto *yytarget[yych];
	}
yy178:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy157;
		if (yych <= '-') goto yy159;
		goto yy160;
	} else {
		if (yych <= '/') goto yy161;
		if (yych == 'a') goto yy182;
		goto yy159;
	}
yy179:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy183;
	goto yy149;
yy180:
	++YYCURSOR;
#line 237 "implicit.re"
	{   char *domain = S_ALLOC_N( char, YYCURSOR - type_id );
                               char *uri;

                               domain[0] = '\0';
                               strncat( domain, type_id, ( YYCURSOR - type_id ) - 1 );
                               uri = syck_taguri( domain, YYCURSOR, YYLIMIT - YYCURSOR );

                               S_FREE( domain );
                               return uri;
                            }
#line 1811 "implicit.c"
yy181:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy184;
	goto yy149;
yy182:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy157;
		if (yych <= '-') goto yy159;
		goto yy160;
	} else {
		if (yych <= '/') goto yy161;
		if (yych == 't') goto yy185;
		goto yy159;
	}
yy183:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy186;
	goto yy149;
yy184:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy187;
	goto yy149;
yy185:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy157;
		if (yych <= '-') goto yy159;
		goto yy160;
	} else {
		if (yych <= '/') goto yy161;
		if (yych == 'e') goto yy188;
		goto yy159;
	}
yy186:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy189;
	if (yych == '/') goto yy180;
	goto yy149;
yy187:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy190;
	goto yy149;
yy188:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy157;
		if (yych <= '-') goto yy159;
		goto yy160;
	} else {
		if (yych <= '/') goto yy161;
		if (yych == ':') goto yy191;
		goto yy159;
	}
yy189:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy192;
	goto yy149;
yy190:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy193;
	if (yych == ':') goto yy194;
	goto yy149;
yy191:
	++YYCURSOR;
#line 220 "implicit.re"
	{   return syck_strndup( type_id, strlen( type_id ) ); }
#line 1884 "implicit.c"
yy192:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy195;
	goto yy149;
yy193:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych <= '9') goto yy196;
	goto yy149;
yy194:
	++YYCURSOR;
#line 218 "implicit.re"
	{   return syck_strndup( type_id, strlen( type_id ) ); }
#line 1899 "implicit.c"
yy195:
	yych = *++YYCURSOR;
	if (yych == '/') goto yy180;
	goto yy149;
yy196:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych >= ':') goto yy149;
	yych = *++YYCURSOR;
	if (yych == '-') goto yy197;
	if (yych == ':') goto yy194;
	goto yy149;
yy197:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych >= ':') goto yy149;
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy149;
	if (yych >= ':') goto yy149;
	yych = *++YYCURSOR;
	if (yych == ':') goto yy194;
	goto yy149;
}
#line 250 "implicit.re"


}
#endif
