/* ex: set ro ft=c: -*- mode: c; buffer-read-only: t -*- *//* Generated by re2c 3.1 */
#line 1 "implicit.re"
/*
 * implicit.re
 *
 * $Author: why $
 * $Date: 2005/11/13 23:43:56 $
 *
 * Copyright (C) 2003 why the lucky stiff
 * Copyright (C) 2026 Reini Urban
 */

#include "syck.h"
#include <string.h>
#include <assert.h>

#define YYCSZ 8
#define YYCTYPE     unsigned char

#define YYCURSOR    cursor
#define YYMARKER    marker
#define YYLIMIT     limit
#define YYFILL(n)   {}

void try_tag_implicit8( SyckNode *n, int taguri );
void try_tag_implicit16( SyckNode *n, int taguri );
void try_tag_implicit32( SyckNode *n, int taguri );

void
try_tag_implicit(const SyckParser *p, SyckNode *n )
{
    switch(p->input_type) {
    case syck_yaml_utf8:
        return try_tag_implicit8(n, p->taguri_expansion);
    case syck_yaml_utf16:
        return try_tag_implicit16(n, p->taguri_expansion);
    case syck_yaml_utf32:
        return try_tag_implicit32(n, p->taguri_expansion);
    case syck_bytecode_utf8:
    case syck_yaml_utf32be:
    case syck_yaml_utf16be:
    default:
        /* unsupported */
        assert(0);
        return;
    }
}

void
try_tag_implicit8( SyckNode *n, int taguri )
{
    const char *tid = "";
    switch ( n->kind )
    {
        case syck_str_kind:
            tid = syck_match_implicit8( (uint8_t*)n->data.str->ptr, n->data.str->len );
            break;

        case syck_seq_kind:
            tid = "seq";
            break;

        case syck_map_kind:
            tid = "map";
            break;

        default:
            break;
    }
    if ( n->type_id != NULL ) {
       S_FREE( n->type_id );
    }
    if ( taguri == 1 )
    {
        n->type_id = syck_taguri( YAML_DOMAIN, tid, strlen( tid ) );
    } else {
        n->type_id = syck_strndup( tid, strlen( tid ) );
    }
}

const char*
syck_match_implicit8
                      ( const YYCTYPE *str, size_t len )
{
    YYCTYPE *marker;
    YYCTYPE *cursor = (YYCTYPE *)str;
    const YYCTYPE *limit = str + len;


#line 119 "implicit.c"
{
	YYCTYPE yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,  76,   0,  32,   0, 
		124, 124, 124, 124, 124, 124, 124, 124, 
		116, 116,   0,   0,   0,   0,   0,   0, 
		  0,  64,  64,  64,  64,  64,  64,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,  64,  64,  64,  64,  64,  64,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((YYLIMIT - YYCURSOR) < 26) YYFILL(26);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy2,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy5,  &&yy3,  &&yy6,  &&yy7,  &&yy3,
			&&yy8,  &&yy9,  &&yy9,  &&yy9,  &&yy9,  &&yy9,  &&yy9,  &&yy9,
			&&yy9,  &&yy9,  &&yy3,  &&yy3,  &&yy10, &&yy11, &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy12, &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy13, &&yy14,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy15, &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy16, &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy17, &&yy3,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy18, &&yy19,
			&&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy20, &&yy3,  &&yy3,  &&yy3,
			&&yy3,  &&yy21, &&yy3,  &&yy3,  &&yy3,  &&yy3,  &&yy22, &&yy3,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy23, &&yy23, &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1
		};
		goto *yytarget[yych];
	}
yy1:
	YYCURSOR = YYMARKER;
	goto yy4;
yy2:
	++YYCURSOR;
#line 152 "implicit.re"
	{   return "null"; }
#line 202 "implicit.c"
yy3:
	++YYCURSOR;
yy4:
#line 174 "implicit.re"
	{   return "str"; }
#line 208 "implicit.c"
yy5:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= '/') {
		if (yych == '.') goto yy24;
		goto yy4;
	} else {
		if (yych <= '0') goto yy25;
		if (yych <= '9') goto yy26;
		goto yy4;
	}
yy6:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= '/') {
		if (yych == '.') goto yy28;
		goto yy4;
	} else {
		if (yych <= '0') goto yy25;
		if (yych <= '9') goto yy26;
		goto yy4;
	}
yy7:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy29, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy30, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy31, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy32, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4
		};
		goto *yytarget[yych];
	}
yy8:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy33, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy34, &&yy4,  &&yy36, &&yy4,
			&&yy37, &&yy37, &&yy37, &&yy37, &&yy37, &&yy37, &&yy37, &&yy37,
			&&yy38, &&yy38, &&yy39, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy40,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy41, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4
		};
		goto *yytarget[yych];
	}
yy9:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy33, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy26, &&yy4,  &&yy36, &&yy4,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy39, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4
		};
		goto *yytarget[yych];
	}
yy10:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == '<') goto yy43;
	goto yy4;
yy11:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy44;
	goto yy4;
yy12:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'A') goto yy45;
	if (yych == 'a') goto yy46;
	goto yy4;
yy13:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy47,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy48, &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy47,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy49, &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4
		};
		goto *yytarget[yych];
	}
yy14:
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy50, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy51, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy52, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy51, &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4
		};
		goto *yytarget[yych];
	}
yy15:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'R') goto yy53;
	if (yych == 'r') goto yy54;
	goto yy4;
yy16:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'E') goto yy55;
	if (yych == 'e') goto yy56;
	goto yy4;
yy17:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'a') goto yy46;
	goto yy4;
yy18:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'o') goto yy47;
	if (yych == 'u') goto yy49;
	goto yy4;
yy19:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'f') goto yy52;
	if (yych == 'n') goto yy51;
	goto yy4;
yy20:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'r') goto yy54;
	goto yy4;
yy21:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'e') goto yy56;
	goto yy4;
yy22:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy2;
	goto yy4;
yy23:
	yych = *++YYCURSOR;
	if (yych <= 0x7F) goto yy1;
	if (yych <= 0xBF) goto yy3;
	goto yy1;
yy24:
	yych = *++YYCURSOR;
	if (yych == 'I') goto yy29;
	if (yych == 'i') goto yy31;
	goto yy1;
yy25:
	yych = *++YYCURSOR;
	if (yych <= 'o') {
		if (yych <= 0x00) goto yy33;
		if (yych <= 'n') goto yy35;
		goto yy40;
	} else {
		if (yych == 'x') goto yy41;
		goto yy35;
	}
yy26:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy27:
	if (yybm[0+yych] & 4) {
		goto yy26;
	}
	if (yych <= '.') {
		if (yych <= 0x00) goto yy33;
		if (yych <= '-') goto yy1;
		goto yy36;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= ':') goto yy39;
		goto yy1;
	}
yy28:
	yych = *++YYCURSOR;
	if (yych == 'I') goto yy59;
	if (yych == 'i') goto yy60;
	goto yy1;
yy29:
	yych = *++YYCURSOR;
	if (yych == 'N') goto yy61;
	if (yych == 'n') goto yy62;
	goto yy1;
yy30:
	yych = *++YYCURSOR;
	if (yych == 'A') goto yy63;
	if (yych == 'a') goto yy63;
	goto yy1;
yy31:
	yych = *++YYCURSOR;
	if (yych == 'n') goto yy62;
	goto yy1;
yy32:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy64;
	goto yy1;
yy33:
	++YYCURSOR;
#line 161 "implicit.re"
	{   return "int"; }
#line 537 "implicit.c"
yy34:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy35:
	if (yybm[0+yych] & 8) {
		goto yy34;
	}
	if (yych <= '.') {
		if (yych <= 0x00) goto yy65;
		if (yych <= '-') goto yy1;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy57;
		if (yych <= ':') goto yy39;
		goto yy1;
	}
yy36:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy66, &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy67, &&yy1,  &&yy68, &&yy1,
			&&yy36, &&yy36, &&yy36, &&yy36, &&yy36, &&yy36, &&yy36, &&yy36,
			&&yy36, &&yy36, &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy69, &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy69, &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,
			&&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1,  &&yy1
		};
		goto *yytarget[yych];
	}
yy37:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy35;
	if (yych <= '7') goto yy70;
	if (yych <= '9') goto yy71;
	goto yy35;
yy38:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy58;
	if (yych <= '9') goto yy71;
	goto yy58;
yy39:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '5') goto yy72;
	if (yych <= '9') goto yy73;
	goto yy1;
yy40:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy1;
	goto yy75;
yy41:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy1;
	goto yy77;
yy42:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy27;
	if (yych <= '9') goto yy78;
	goto yy27;
yy43:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy79;
	goto yy1;
yy44:
	++YYCURSOR;
#line 172 "implicit.re"
	{   return "default"; }
#line 636 "implicit.c"
yy45:
	yych = *++YYCURSOR;
	if (yych == 'L') goto yy80;
	goto yy1;
yy46:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy81;
	goto yy1;
yy47:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy82;
	goto yy1;
yy48:
	yych = *++YYCURSOR;
	if (yych == 'L') goto yy83;
	goto yy1;
yy49:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy84;
	goto yy1;
yy50:
	yych = *++YYCURSOR;
	if (yych == 'F') goto yy47;
	goto yy1;
yy51:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy85;
	goto yy1;
yy52:
	yych = *++YYCURSOR;
	if (yych == 'f') goto yy47;
	goto yy1;
yy53:
	yych = *++YYCURSOR;
	if (yych == 'U') goto yy86;
	goto yy1;
yy54:
	yych = *++YYCURSOR;
	if (yych == 'u') goto yy87;
	goto yy1;
yy55:
	yych = *++YYCURSOR;
	if (yych == 'S') goto yy51;
	goto yy1;
yy56:
	yych = *++YYCURSOR;
	if (yych == 's') goto yy51;
	goto yy1;
yy57:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy58:
	if (yych <= '.') {
		if (yych == ',') goto yy57;
		if (yych <= '-') goto yy1;
		goto yy36;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy57;
		if (yych <= ':') goto yy39;
		goto yy1;
	}
yy59:
	yych = *++YYCURSOR;
	if (yych == 'N') goto yy88;
	if (yych == 'n') goto yy89;
	goto yy1;
yy60:
	yych = *++YYCURSOR;
	if (yych == 'n') goto yy89;
	goto yy1;
yy61:
	yych = *++YYCURSOR;
	if (yych == 'F') goto yy90;
	goto yy1;
yy62:
	yych = *++YYCURSOR;
	if (yych == 'f') goto yy90;
	goto yy1;
yy63:
	yych = *++YYCURSOR;
	if (yych == 'N') goto yy91;
	goto yy1;
yy64:
	yych = *++YYCURSOR;
	if (yych == 'n') goto yy91;
	goto yy1;
yy65:
	++YYCURSOR;
#line 158 "implicit.re"
	{   return "int#oct"; }
#line 729 "implicit.c"
yy66:
	++YYCURSOR;
#line 162 "implicit.re"
	{   return "float#fix"; }
#line 734 "implicit.c"
yy67:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= ',') {
		if (yych <= 0x00) goto yy66;
		if (yych <= '+') goto yy1;
		goto yy67;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy67;
		goto yy1;
	}
yy68:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 32) {
		goto yy68;
	}
	if (yych == 'E') goto yy69;
	if (yych != 'e') goto yy1;
yy69:
	yych = *++YYCURSOR;
	if (yych == '+') goto yy92;
	if (yych == '-') goto yy92;
	goto yy1;
yy70:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy35;
	if (yych <= '7') goto yy93;
	if (yych <= '9') goto yy94;
	goto yy35;
yy71:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy58;
	if (yych <= '9') goto yy94;
	goto yy58;
yy72:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= '.') {
		if (yych <= 0x00) goto yy95;
		if (yych <= '-') goto yy1;
		goto yy96;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy73;
		if (yych <= ':') goto yy39;
		goto yy1;
	}
yy73:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= '.') {
		if (yych <= 0x00) goto yy95;
		if (yych <= '-') goto yy1;
		goto yy96;
	} else {
		if (yych == ':') goto yy39;
		goto yy1;
	}
yy74:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy75:
	if (yych <= ',') {
		if (yych <= 0x00) goto yy97;
		if (yych <= '+') goto yy1;
		goto yy74;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= '7') goto yy74;
		goto yy1;
	}
yy76:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy77:
	if (yybm[0+yych] & 64) {
		goto yy76;
	}
	if (yych <= 0x00) goto yy98;
	goto yy1;
yy78:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy27;
	if (yych <= '9') goto yy99;
	goto yy27;
yy79:
	++YYCURSOR;
#line 173 "implicit.re"
	{   return "merge"; }
#line 832 "implicit.c"
yy80:
	yych = *++YYCURSOR;
	if (yych == 'S') goto yy100;
	goto yy1;
yy81:
	yych = *++YYCURSOR;
	if (yych == 's') goto yy101;
	goto yy1;
yy82:
	++YYCURSOR;
#line 154 "implicit.re"
	{   return "bool#no"; }
#line 845 "implicit.c"
yy83:
	yych = *++YYCURSOR;
	if (yych == 'L') goto yy102;
	goto yy1;
yy84:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy102;
	goto yy1;
yy85:
	++YYCURSOR;
#line 153 "implicit.re"
	{   return "bool#yes"; }
#line 858 "implicit.c"
yy86:
	yych = *++YYCURSOR;
	if (yych == 'E') goto yy51;
	goto yy1;
yy87:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy51;
	goto yy1;
yy88:
	yych = *++YYCURSOR;
	if (yych == 'F') goto yy103;
	goto yy1;
yy89:
	yych = *++YYCURSOR;
	if (yych == 'f') goto yy103;
	goto yy1;
yy90:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy104;
	goto yy1;
yy91:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy105;
	goto yy1;
yy92:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy1;
	goto yy107;
yy93:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy108;
	goto yy35;
yy94:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy108;
	goto yy58;
yy95:
	++YYCURSOR;
#line 160 "implicit.re"
	{   return "int#base60"; }
#line 899 "implicit.c"
yy96:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= ',') {
		if (yych <= 0x00) goto yy109;
		if (yych <= '+') goto yy1;
		goto yy96;
	} else {
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy96;
		goto yy1;
	}
yy97:
	++YYCURSOR;
#line 159 "implicit.re"
	{   return "int#oct"; }
#line 917 "implicit.c"
yy98:
	++YYCURSOR;
#line 157 "implicit.re"
	{   return "int#hex"; }
#line 922 "implicit.c"
yy99:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy108;
	goto yy27;
yy100:
	yych = *++YYCURSOR;
	if (yych == 'E') goto yy47;
	goto yy1;
yy101:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy47;
	goto yy1;
yy102:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy2;
	goto yy1;
yy103:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy110;
	goto yy1;
yy104:
	++YYCURSOR;
#line 165 "implicit.re"
	{   return "float#inf"; }
#line 947 "implicit.c"
yy105:
	++YYCURSOR;
#line 167 "implicit.re"
	{   return "float#nan"; }
#line 952 "implicit.c"
yy106:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy107:
	if (yych <= 0x00) goto yy111;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy106;
	goto yy1;
yy108:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy112;
	goto yy1;
yy109:
	++YYCURSOR;
#line 164 "implicit.re"
	{   return "float#base60"; }
#line 971 "implicit.c"
yy110:
	++YYCURSOR;
#line 166 "implicit.re"
	{   return "float#neginf"; }
#line 976 "implicit.c"
yy111:
	++YYCURSOR;
#line 163 "implicit.re"
	{   return "float#exp"; }
#line 981 "implicit.c"
yy112:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych >= ':') goto yy1;
	yych = *++YYCURSOR;
	if (yych != '-') goto yy1;
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych >= ':') goto yy1;
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych >= ':') goto yy1;
	yych = *++YYCURSOR;
	if (yych <= 'S') {
		if (yych <= 0x00) goto yy113;
		if (yych <= '/') goto yy115;
		if (yych <= '9') goto yy1;
		goto yy115;
	} else {
		if (yych <= 'T') goto yy116;
		if (yych == 't') goto yy116;
		goto yy115;
	}
yy113:
	++YYCURSOR;
#line 168 "implicit.re"
	{   return "timestamp#ymd"; }
#line 1009 "implicit.c"
yy114:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
	yych = *YYCURSOR;
yy115:
	if (yybm[0+yych] & 128) {
		goto yy114;
	}
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy117;
	goto yy1;
yy116:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy118;
	goto yy1;
yy117:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy119;
	goto yy1;
yy118:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy120;
	goto yy1;
yy119:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy121;
	goto yy1;
yy120:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy122;
	goto yy1;
yy121:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy123;
	goto yy1;
yy122:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy124;
	goto yy1;
yy123:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy125;
	goto yy1;
yy124:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy126;
	goto yy1;
yy125:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy127;
	goto yy1;
yy126:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy128;
	goto yy1;
yy127:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy129;
	goto yy1;
yy128:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy130;
	goto yy1;
yy129:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy131;
	goto yy1;
yy130:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy132;
	goto yy1;
yy131:
	yych = *++YYCURSOR;
	if (yych == '.') goto yy134;
	if (yych <= '/') goto yy135;
	if (yych <= '9') goto yy1;
	goto yy135;
yy132:
	yych = *++YYCURSOR;
	if (yych == '.') goto yy137;
	if (yych <= '/') goto yy138;
	if (yych <= '9') goto yy1;
	goto yy138;
yy133:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy133, &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy133, &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy140, &&yy1,   &&yy140, &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy141, &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1
		};
		goto *yytarget[yych];
	}
yy134:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy135:
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy133;
		goto yy1;
	} else {
		if (yych <= ' ') goto yy133;
		if (yych <= '/') goto yy1;
		if (yych <= '9') goto yy134;
		goto yy1;
	}
yy136:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy142;
	goto yy1;
yy137:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
yy138:
	{
		static void *yytarget[256] = {
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy136, &&yy1,   &&yy136, &&yy1,   &&yy1,
			&&yy137, &&yy137, &&yy137, &&yy137, &&yy137, &&yy137, &&yy137, &&yy137,
			&&yy137, &&yy137, &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy139, &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,
			&&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1,   &&yy1
		};
		goto *yytarget[yych];
	}
yy139:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy143;
	goto yy1;
yy140:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy144;
	goto yy1;
yy141:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy145;
	goto yy1;
yy142:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy146;
	goto yy1;
yy143:
	++YYCURSOR;
#line 169 "implicit.re"
	{   return "timestamp#iso8601"; }
#line 1228 "implicit.c"
yy144:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy147;
	goto yy1;
yy145:
	++YYCURSOR;
#line 170 "implicit.re"
	{   return "timestamp#spaced"; }
#line 1238 "implicit.c"
yy146:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy143;
	if (yych == ':') goto yy148;
	goto yy1;
yy147:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy145;
	if (yych == ':') goto yy149;
	goto yy1;
yy148:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy150;
	goto yy1;
yy149:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy151;
	goto yy1;
yy150:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy139;
	goto yy1;
yy151:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy1;
	if (yych <= '9') goto yy141;
	goto yy1;
}
#line 176 "implicit.re"


}

/* Remove ending fragment and compare types */
int
syck_tagcmp( const char *tag1, const char *tag2 )
{
    if ( tag1 == tag2 ) return 1;
    if ( tag1 == NULL || tag2 == NULL ) return 0;
    else {
        int i;
        char *othorpe;
        char *tmp1 = syck_strndup( tag1, strlen( tag1 ) );
        char *tmp2 = syck_strndup( tag2, strlen( tag2 ) );
        othorpe = strstr( tmp1, "#" );
        if ( othorpe != NULL ) {
            othorpe[0] = '\0';
        }
        othorpe = strstr( tmp2, "#" );
        if ( othorpe != NULL ) {
            othorpe[0] = '\0';
        }
        i = strcmp( tmp1, tmp2 );
        S_FREE( tmp1 ); S_FREE( tmp2 );
        return i;
    }
}

char *
syck_type_id_to_uri( char *type_id )
{
    char *cursor, *limit, *marker = NULL;

    cursor = type_id;
    limit = type_id + strlen( type_id );


#line 1310 "implicit.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,  64,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0, 128, 
		  0, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	if ((YYLIMIT - YYCURSOR) < 21) YYFILL(21);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy153, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154,
			&&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154,
			&&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154,
			&&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154,
			&&yy154, &&yy156, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154,
			&&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154,
			&&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158,
			&&yy158, &&yy158, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154,
			&&yy154, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158,
			&&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158,
			&&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158,
			&&yy158, &&yy158, &&yy158, &&yy154, &&yy154, &&yy154, &&yy154, &&yy158,
			&&yy154, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158,
			&&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158, &&yy158,
			&&yy158, &&yy158, &&yy158, &&yy158, &&yy159, &&yy158, &&yy158, &&yy158,
			&&yy160, &&yy158, &&yy158, &&yy154, &&yy154, &&yy154, &&yy154, &&yy154,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy161, &&yy161, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153
		};
		goto *yytarget[yych];
	}
yy153:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy157;
	} else {
		goto yy155;
	}
yy154:
	++YYCURSOR;
yy155:
#line 270 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, type_id, strlen( type_id ) ); }
#line 1399 "implicit.c"
yy156:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy162, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy163, &&yy157, &&yy157, &&yy157, &&yy164, &&yy157,
			&&yy157, &&yy165, &&yy157, &&yy157, &&yy157, &&yy166, &&yy167, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy168, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157,
			&&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157, &&yy157
		};
		goto *yytarget[yych];
	}
yy157:
#line 244 "implicit.re"
	{   return syck_xprivate( type_id + 1, strlen( type_id ) - 1 ); }
#line 1443 "implicit.c"
yy158:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy155, &&yy155, &&yy155, &&yy155, &&yy175,
			&&yy155, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155
		};
		goto *yytarget[yych];
	}
yy159:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy155, &&yy155, &&yy155, &&yy155, &&yy175,
			&&yy155, &&yy176, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155
		};
		goto *yytarget[yych];
	}
yy160:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	{
		static void *yytarget[256] = {
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy175, &&yy177, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy155, &&yy155, &&yy155, &&yy155, &&yy175,
			&&yy155, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175, &&yy175,
			&&yy175, &&yy175, &&yy175, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155,
			&&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155, &&yy155
		};
		goto *yytarget[yych];
	}
yy161:
	yych = *++YYCURSOR;
	if (yych <= 0x7F) goto yy153;
	if (yych <= 0xBF) goto yy154;
	goto yy153;
yy162:
	yych = *++YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy178, &&yy153, &&yy153, &&yy153, &&yy179, &&yy153,
			&&yy153, &&yy180, &&yy153, &&yy153, &&yy153, &&yy181, &&yy182, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy183, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153
		};
		goto *yytarget[yych];
	}
yy163:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy184;
	goto yy153;
yy164:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy185;
	goto yy153;
yy165:
	yych = *++YYCURSOR;
	if (yych == 'n') goto yy186;
	goto yy153;
yy166:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy187;
	goto yy153;
yy167:
	yych = *++YYCURSOR;
	if (yych == 'u') goto yy188;
	goto yy153;
yy168:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy189;
	if (yych == 't') goto yy190;
	goto yy153;
yy169:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy191;
	goto yy153;
yy170:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy171:
	if (yybm[0+yych] & 64) {
		goto yy170;
	}
	if (yych <= 'Z') {
		if (yych <= '/') goto yy153;
		if (yych <= '9') goto yy174;
		if (yych <= '@') goto yy153;
		goto yy174;
	} else {
		if (yych <= '_') {
			if (yych <= '^') goto yy153;
			goto yy174;
		} else {
			if (yych <= '`') goto yy153;
			if (yych <= 'z') goto yy174;
			goto yy153;
		}
	}
yy172:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy174;
	}
	goto yy153;
yy173:
	++YYCURSOR;
#line 246 "implicit.re"
	{   char *domain = S_ALLOC_N( char, ( YYCURSOR - type_id ) + 15 );
                    char *uri;

                    domain[0] = '\0';
                    strncat( domain, type_id, ( YYCURSOR - type_id ) - 1 );
                    strcat( domain, "." );
                    strcat( domain, YAML_DOMAIN );
                    uri = syck_taguri( domain, YYCURSOR, YYLIMIT - YYCURSOR );

                    S_FREE( domain );
                    return uri;
                }
#line 1684 "implicit.c"
yy174:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 12) YYFILL(12);
	yych = *YYCURSOR;
yy175:
	if (yybm[0+yych] & 64) {
		goto yy170;
	}
	if (yych <= '@') {
		if (yych <= '.') {
			if (yych <= '+') goto yy153;
			if (yych <= ',') goto yy169;
			goto yy172;
		} else {
			if (yych <= '/') goto yy173;
			if (yych <= '9') goto yy174;
			goto yy153;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy174;
			if (yych <= '^') goto yy153;
			goto yy174;
		} else {
			if (yych <= '`') goto yy153;
			if (yych <= 'z') goto yy174;
			goto yy153;
		}
	}
yy176:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy169;
		if (yych <= '-') goto yy171;
		goto yy172;
	} else {
		if (yych <= '/') goto yy173;
		if (yych == 'g') goto yy192;
		goto yy171;
	}
yy177:
	yych = *++YYCURSOR;
	if (yych == 'p') goto yy193;
	goto yy171;
yy178:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy194;
	goto yy153;
yy179:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy195;
	goto yy153;
yy180:
	yych = *++YYCURSOR;
	if (yych == 'n') goto yy196;
	goto yy153;
yy181:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy197;
	goto yy153;
yy182:
	yych = *++YYCURSOR;
	if (yych == 'u') goto yy198;
	goto yy153;
yy183:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy199;
	if (yych == 't') goto yy200;
	goto yy153;
yy184:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy201;
	goto yy153;
yy185:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy202;
	goto yy153;
yy186:
	yych = *++YYCURSOR;
	if (yych == 't') goto yy203;
	goto yy153;
yy187:
	yych = *++YYCURSOR;
	if (yych == 'p') goto yy204;
	goto yy153;
yy188:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy205;
	goto yy153;
yy189:
	yych = *++YYCURSOR;
	if (yych == 'q') goto yy206;
	goto yy153;
yy190:
	yych = *++YYCURSOR;
	if (yych == 'r') goto yy207;
	goto yy153;
yy191:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy208;
	goto yy153;
yy192:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy169;
		if (yych <= '-') goto yy171;
		goto yy172;
	} else {
		if (yych <= '/') goto yy173;
		if (yych == ':') goto yy209;
		goto yy171;
	}
yy193:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy169;
		if (yych <= '-') goto yy171;
		goto yy172;
	} else {
		if (yych <= '/') goto yy173;
		if (yych == 'r') goto yy210;
		goto yy171;
	}
yy194:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy211;
	goto yy153;
yy195:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy212;
	goto yy153;
yy196:
	yych = *++YYCURSOR;
	if (yych == 't') goto yy213;
	goto yy153;
yy197:
	yych = *++YYCURSOR;
	if (yych == 'p') goto yy214;
	goto yy153;
yy198:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy215;
	goto yy153;
yy199:
	yych = *++YYCURSOR;
	if (yych == 'q') goto yy216;
	goto yy153;
yy200:
	yych = *++YYCURSOR;
	if (yych == 'r') goto yy217;
	goto yy153;
yy201:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy218;
	goto yy153;
yy202:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy219;
	goto yy153;
yy203:
	++YYCURSOR;
#line 229 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "int", 5 ); }
#line 1849 "implicit.c"
yy204:
	++YYCURSOR;
#line 231 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "map", 5 ); }
#line 1854 "implicit.c"
yy205:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy220;
	goto yy153;
yy206:
	++YYCURSOR;
#line 230 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "seq", 5 ); }
#line 1863 "implicit.c"
yy207:
	++YYCURSOR;
#line 228 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "str", 5 ); }
#line 1868 "implicit.c"
yy208:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy221;
	goto yy153;
yy209:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy153, &&yy153, &&yy153, &&yy153, &&yy222,
			&&yy153, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153
		};
		goto *yytarget[yych];
	}
yy210:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy169;
		if (yych <= '-') goto yy171;
		goto yy172;
	} else {
		if (yych <= '/') goto yy173;
		if (yych == 'i') goto yy223;
		goto yy171;
	}
yy211:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy224;
	goto yy153;
yy212:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy225;
	goto yy153;
yy213:
	++YYCURSOR;
#line 237 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "int", 5 ); }
#line 1938 "implicit.c"
yy214:
	++YYCURSOR;
#line 239 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "map", 5 ); }
#line 1943 "implicit.c"
yy215:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy226;
	goto yy153;
yy216:
	++YYCURSOR;
#line 238 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "seq", 5 ); }
#line 1952 "implicit.c"
yy217:
	++YYCURSOR;
#line 236 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "str", 5 ); }
#line 1957 "implicit.c"
yy218:
	++YYCURSOR;
#line 232 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "bool", 6 ); }
#line 1962 "implicit.c"
yy219:
	yych = *++YYCURSOR;
	if (yych == 't') goto yy227;
	goto yy153;
yy220:
	++YYCURSOR;
#line 233 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "null", 6 ); }
#line 1971 "implicit.c"
yy221:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy228;
	goto yy153;
yy222:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 12) YYFILL(12);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy229, &&yy230, &&yy209, &&yy153,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy153, &&yy153, &&yy153, &&yy153, &&yy222,
			&&yy153, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153
		};
		goto *yytarget[yych];
	}
yy223:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy169;
		if (yych <= '-') goto yy171;
		goto yy172;
	} else {
		if (yych <= '/') goto yy173;
		if (yych == 'v') goto yy231;
		goto yy171;
	}
yy224:
	++YYCURSOR;
#line 240 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "bool", 6 ); }
#line 2033 "implicit.c"
yy225:
	yych = *++YYCURSOR;
	if (yych == 't') goto yy232;
	goto yy153;
yy226:
	++YYCURSOR;
#line 241 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "null", 6 ); }
#line 2042 "implicit.c"
yy227:
	++YYCURSOR;
#line 234 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "float", 7 ); }
#line 2047 "implicit.c"
yy228:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy233;
	if (yych == '/') goto yy234;
	goto yy153;
yy229:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy235;
	goto yy153;
yy230:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy230, &&yy153, &&yy153,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy153, &&yy153, &&yy153, &&yy153, &&yy222,
			&&yy153, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222, &&yy222,
			&&yy222, &&yy222, &&yy222, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153,
			&&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153, &&yy153
		};
		goto *yytarget[yych];
	}
yy231:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy169;
		if (yych <= '-') goto yy171;
		goto yy172;
	} else {
		if (yych <= '/') goto yy173;
		if (yych == 'a') goto yy236;
		goto yy171;
	}
yy232:
	++YYCURSOR;
#line 242 "implicit.re"
	{   return syck_taguri( YAML_DOMAIN, "float", 7 ); }
#line 2114 "implicit.c"
yy233:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy237;
	goto yy153;
yy234:
	++YYCURSOR;
#line 259 "implicit.re"
	{   char *domain = S_ALLOC_N( char, YYCURSOR - type_id );
                               char *uri;

                               domain[0] = '\0';
                               strncat( domain, type_id, ( YYCURSOR - type_id ) - 1 );
                               uri = syck_taguri( domain, YYCURSOR, YYLIMIT - YYCURSOR );

                               S_FREE( domain );
                               return uri;
                            }
#line 2133 "implicit.c"
yy235:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy238;
	goto yy153;
yy236:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy169;
		if (yych <= '-') goto yy171;
		goto yy172;
	} else {
		if (yych <= '/') goto yy173;
		if (yych == 't') goto yy239;
		goto yy171;
	}
yy237:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy240;
	goto yy153;
yy238:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy241;
	goto yy153;
yy239:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy169;
		if (yych <= '-') goto yy171;
		goto yy172;
	} else {
		if (yych <= '/') goto yy173;
		if (yych == 'e') goto yy242;
		goto yy171;
	}
yy240:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy243;
	if (yych == '/') goto yy234;
	goto yy153;
yy241:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy244;
	goto yy153;
yy242:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych == ',') goto yy169;
		if (yych <= '-') goto yy171;
		goto yy172;
	} else {
		if (yych <= '/') goto yy173;
		if (yych == ':') goto yy245;
		goto yy171;
	}
yy243:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy246;
	goto yy153;
yy244:
	yych = *++YYCURSOR;
	if (yych == '-') goto yy247;
	if (yych == ':') goto yy248;
	goto yy153;
yy245:
	++YYCURSOR;
#line 226 "implicit.re"
	{   return syck_strndup( type_id, strlen( type_id ) ); }
#line 2206 "implicit.c"
yy246:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy249;
	goto yy153;
yy247:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych <= '9') goto yy250;
	goto yy153;
yy248:
	++YYCURSOR;
#line 224 "implicit.re"
	{   return syck_strndup( type_id, strlen( type_id ) ); }
#line 2221 "implicit.c"
yy249:
	yych = *++YYCURSOR;
	if (yych == '/') goto yy234;
	goto yy153;
yy250:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych >= ':') goto yy153;
	yych = *++YYCURSOR;
	if (yych == '-') goto yy251;
	if (yych == ':') goto yy248;
	goto yy153;
yy251:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych >= ':') goto yy153;
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy153;
	if (yych >= ':') goto yy153;
	yych = *++YYCURSOR;
	if (yych == ':') goto yy248;
	goto yy153;
}
#line 272 "implicit.re"


}
