/* ex: set ro ft=c: -*- mode: c; buffer-read-only: t -*- */
/* Generated by re2c 3.1 */
#line 1 "token.re"
/*
 * token.re
 *
 * $Author: why $
 * $Date: 2005-09-21 02:42:51 +0300 (Wed, 21 Sep 2005) $
 *
 * Copyright (C) 2003 why the lucky stiff
 */
#include "syck.h"
#include "gram.h"
#include "bytecode.h"
#include <assert.h>
#include <string.h>
#include <ctype.h>

/*
 * Allocate quoted strings in chunks
 */
#define QUOTELEN    1024

/*
 * They do my bidding...
 */
#define YYCTYPE     char
#define YYCURSOR    parser->cursor
#define YYMARKER    parser->marker
#define YYLIMIT     parser->limit
#define YYTOKEN     parser->token
#define YYTOKTMP    parser->toktmp
#define YYLINEPTR   parser->lineptr
#define YYLINECTPTR parser->linectptr
#define YYLINE      parser->linect
#define YYFILL(n)   syck_parser_read(parser)

/*
 * Repositions the cursor at `n' offset from the token start.
 * Only works in `Header' and `Document' sections.
 */
#define YYPOS(n)    YYCURSOR = YYTOKEN + n

/*
 * Track line numbers
 */
#define NEWLINE(ptr) \
        YYLINEPTR = ptr + newline_len(ptr); \
        if ( YYLINEPTR > YYLINECTPTR ) { YYLINE++; YYLINECTPTR = YYLINEPTR; }

/*
 * I like seeing the level operations as macros...
 */
#define ADD_LEVEL(len, status)  syck_parser_add_level( parser, len, status )
#define POP_LEVEL()     syck_parser_pop_level( parser )
#define CURRENT_LEVEL() syck_parser_current_level( parser )

/*
 * Force a token next time around sycklex()
 */
#define FORCE_NEXT_TOKEN(tok)    parser->force_token = tok;

/*
 * Nice little macro to ensure we're YAML_IOPENed to the current level.
 * * Only use this macro in the "Document" section *
 */
#define ENSURE_YAML_IOPEN(last_lvl, to_len, reset) \
        if ( last_lvl->spaces < to_len ) \
        { \
            if ( last_lvl->status == syck_lvl_iseq || last_lvl->status == syck_lvl_imap ) \
            { \
                goto Document; \
            } \
            else \
            { \
                ADD_LEVEL( to_len, syck_lvl_doc ); \
                if ( reset == 1 ) YYPOS(0); \
                return YAML_IOPEN; \
            } \
        }

/*
 * Nice little macro to ensure closure of levels.
 * * Only use this macro in the "Document" section *
 */
#define ENSURE_YAML_IEND(last_lvl, to_len) \
        if ( last_lvl->spaces > to_len ) \
        { \
            syck_parser_pop_level( parser ); \
            YYPOS(0); \
            return YAML_IEND; \
        }

/*
 * Concatenates quoted string items and manages allocation
 * to the quoted string
 */
#define QUOTECAT(s, c, i, l) \
        { \
            if ( i + 1 >= c ) \
            { \
                c += QUOTELEN; \
                S_REALLOC_N( s, char, c ); \
            } \
            s[i++] = l; \
            s[i] = '\0'; \
        }

#define QUOTECATS(s, c, i, cs, cl) \
        { \
            while ( i + cl >= c ) \
            { \
                c += QUOTELEN; \
                S_REALLOC_N( s, char, c ); \
            } \
            S_MEMCPY( s + i, cs, char, cl ); \
            i += cl; \
            s[i] = '\0'; \
        }

/*
 * Tags a plain scalar with a transfer method
 * * Use only in "Plain" section *
 */
#define RETURN_IMPLICIT() \
    { \
        SyckNode *n = syck_alloc_str(); \
        YYCURSOR = YYTOKEN; \
        n->data.str->ptr = qstr; \
        n->data.str->len = qidx; \
        n->data.str->style = scalar_plain; \
        sycklval->nodeData = n; \
        if ( parser->implicit_typing == 1 ) \
        { \
            try_tag_implicit( sycklval->nodeData, parser->taguri_expansion ); \
        } \
        return YAML_PLAIN; \
    }

/* concat the inline characters to the plain scalar */
#define PLAIN_NOT_INL() \
    if ( *(YYCURSOR - 1) == ' ' || is_newline( YYCURSOR - 1 ) ) \
    { \
        YYCURSOR--; \
    } \
    QUOTECATS(qstr, qcapa, qidx, YYTOKEN, YYCURSOR - YYTOKEN); \
    goto Plain2;

/* trim spaces off the end in case of indent */
#define PLAIN_IS_INL() \
    char *walker = qstr + qidx - 1; \
    while ( walker > qstr && ( *walker == '\n' || *walker == ' ' || *walker == '\t' ) ) \
    { \
        qidx--; \
        walker[0] = '\0'; \
        walker--; \
    }

/*
 * Keep or chomp block?
 * * Use only in "ScalarBlock" section *
 */
#define RETURN_YAML_BLOCK() \
    { \
        SyckNode *n = syck_alloc_str(); \
        if ( ((SyckParser *)parser)->taguri_expansion == 1 ) \
        { \
            n->type_id = syck_taguri( YAML_DOMAIN, "str", 3 ); \
        } \
        else \
        { \
            n->type_id = syck_strndup( "str", 3 ); \
        } \
        n->data.str->ptr = qstr; \
        n->data.str->len = qidx; \
        if ( blockType == BLOCK_LIT ) { \
            n->data.str->style = scalar_literal; \
        } else { \
            n->data.str->style = scalar_fold; \
        } \
        if ( qidx > 0 ) \
        { \
            if ( nlDoWhat != NL_KEEP ) \
            { \
                char *fc = n->data.str->ptr + n->data.str->len - 1; \
                while ( is_newline( fc ) ) fc--; \
                if ( nlDoWhat != NL_CHOMP && fc < n->data.str->ptr + n->data.str->len - 1 ) \
                    fc += 1; \
                n->data.str->len = fc - n->data.str->ptr + 1; \
            } \
        } \
        sycklval->nodeData = n; \
        return YAML_BLOCK; \
    }

/*
 * Handles newlines, calculates indent
 */
#define GOBBLE_UP_YAML_INDENT( ict, start ) \
    char *indent = start; \
    NEWLINE(indent); \
    while ( indent < YYCURSOR ) \
    { \
        if ( is_newline( ++indent ) ) \
        { \
            NEWLINE(indent); \
        } \
    } \
    ict = 0; \
    if ( *YYCURSOR == '\0' ) \
    { \
        ict = -1; \
        start = YYCURSOR - 1; \
    } \
    else if ( *YYLINEPTR == ' ' ) \
    { \
        ict = YYCURSOR - YYLINEPTR; \
    }

/*
 * If an indent exists at the current level, back up.
 */
#define GET_TRUE_YAML_INDENT(indt_len) \
    { \
        SyckLevel *lvl_deep = CURRENT_LEVEL(); \
        indt_len = lvl_deep->spaces; \
        if ( lvl_deep->status == syck_lvl_seq || ( indt_len == YYCURSOR - YYLINEPTR && lvl_deep->status != syck_lvl_map )  ) \
        { \
            SyckLevel *lvl_over; \
            parser->lvl_idx--; \
            lvl_over = CURRENT_LEVEL(); \
            indt_len = lvl_over->spaces; \
            parser->lvl_idx++; \
        } \
    }

/*
 * Accessory funcs later in this file.
 */
int syckwrap(void);
static void eat_comments( SyckParser *parser );

static int
newline_len( char *ptr )
{
    if ( *ptr == '\n' )
        return 1;

    if ( *ptr == '\r' && *( ptr + 1 ) == '\n' )
        return 2;

    return 0;
}

static int
is_newline( char *ptr )
{
    return newline_len( ptr );
}

static char
escape_seq( char ch )
{
    switch ( ch )
    {
        case '0': return '\0';
        case 'a': return 7;
        case 'b': return '\010';
        case 'e': return '\033';
        case 'f': return '\014';
        case 'n': return '\n';
        case 'r': return '\015';
        case 't': return '\t';
        case 'v': return '\013';
        default: return ch;
    }
}

/*
 * My own re-entrant sycklex() using re2c.
 * You really get used to the limited regexp.
 * It's really nice to not rely on backtracking and such.
 */
int
sycklex( YYSTYPE *sycklval, SyckParser *parser )
{
    assert(parser);
    switch ( parser->input_type )
    {
        case syck_yaml_utf8:
            return sycklex_yaml_utf8( sycklval, parser );

        case syck_yaml_utf16:
            syckerror( parser, "UTF-16 is not currently supported in Syck.\nPlease contribute code to help this happen!" );
            break;

        case syck_yaml_utf32:
            syckerror( parser, "UTF-32 is not currently supported in Syck.\nPlease contribute code to help this happen!" );
            break;

        case syck_bytecode_utf8:
            return sycklex_bytecode_utf8( sycklval, parser );

        default:
            break;
    }
    return YAML_DOCSEP;
}

/*
 * Parser for standard YAML [UTF-8]
 */
int
sycklex_yaml_utf8( YYSTYPE *sycklval, SyckParser *parser )
{
    int doc_level = 0;
    if ( YYCURSOR == NULL )
    {
        syck_parser_read( parser );
    }

    if ( parser->force_token != 0 )
    {
        int t = parser->force_token;
        parser->force_token = 0;
        return t;
    }

#line 351 "token.re"


    if ( YYLINEPTR != YYCURSOR )
    {
        goto Document;
    }

Header:

    YYTOKEN = YYCURSOR;


#line 342 "token.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 11) YYFILL(11);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case ' ': goto yy4;
		case '\n': goto yy6;
		case '\r': goto yy8;
		case '#': goto yy9;
		case '%': goto yy10;
		case '-': goto yy11;
		case '.': goto yy12;
		default: goto yy2;
	}
yy1:
	++YYCURSOR;
#line 396 "token.re"
	{   SyckLevel *lvl = CURRENT_LEVEL();
                        ENSURE_YAML_IEND(lvl, -1);
                        YYPOS(0);
                        return 0;
                    }
#line 368 "token.c"
yy2:
	++YYCURSOR;
yy3:
#line 415 "token.re"
	{   YYPOS(0);
                        goto Document;
                    }
#line 376 "token.c"
yy4:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\t':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
#line 411 "token.re"
	{   doc_level = YYCURSOR - YYLINEPTR;
                        goto Header;
                    }
#line 391 "token.c"
yy6:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n':
		case ' ': goto yy6;
		case '\r': goto yy13;
		default: goto yy7;
	}
yy7:
#line 407 "token.re"
	{   GOBBLE_UP_YAML_INDENT( doc_level, YYTOKEN );
                        goto Header;
                    }
#line 408 "token.c"
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy6;
		default: goto yy3;
	}
yy9:
	++YYCURSOR;
#line 392 "token.re"
	{   eat_comments( parser );
                        goto Header;
                    }
#line 421 "token.c"
yy10:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'Y': goto yy15;
		default: goto yy3;
	}
yy11:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '-': goto yy16;
		default: goto yy3;
	}
yy12:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.': goto yy17;
		default: goto yy3;
	}
yy13:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n': goto yy6;
		default: goto yy14;
	}
yy14:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy7;
	} else {
		goto yy3;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A': goto yy18;
		default: goto yy14;
	}
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy19;
		default: goto yy14;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy20;
		default: goto yy14;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'M': goto yy21;
		default: goto yy14;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy22;
		case '\r': goto yy24;
		case ' ': goto yy25;
		default: goto yy14;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy26;
		case '\r': goto yy28;
		case ' ': goto yy29;
		default: goto yy14;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy30;
		default: goto yy14;
	}
yy22:
	++YYCURSOR;
yy23:
#line 364 "token.re"
	{   SyckLevel *lvl = CURRENT_LEVEL();
                        if ( lvl->status == syck_lvl_header )
                        {
                            YYPOS(3);
                            goto Directive;
                        }
                        else
                        {
                            ENSURE_YAML_IEND(lvl, -1);
                            YYPOS(0);
                            return 0;
                        }
                    }
#line 521 "token.c"
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy22;
		default: goto yy14;
	}
yy25:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy25;
		default: goto yy23;
	}
yy26:
	++YYCURSOR;
yy27:
#line 378 "token.re"
	{   SyckLevel *lvl = CURRENT_LEVEL();
                        if ( lvl->status == syck_lvl_header )
                        {
                            goto Header;
                        }
                        else
                        {
                            ENSURE_YAML_IEND(lvl, -1);
                            YYPOS(0);
                            return 0;
                        }
                        return 0;
                    }
#line 553 "token.c"
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy26;
		default: goto yy14;
	}
yy29:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy29;
		default: goto yy27;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy31;
		default: goto yy14;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1': goto yy32;
		default: goto yy14;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy33;
		default: goto yy14;
	}
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy34;
		default: goto yy14;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy35;
		case '\r': goto yy37;
		case ' ': goto yy38;
		default: goto yy14;
	}
yy35:
	++YYCURSOR;
yy36:
#line 402 "token.re"
	{   sycklval->name = syck_strndup( YYTOKEN + 6, YYCURSOR - YYTOKEN - 7);
                        DPRINTF ((stderr, "DEBUG '%%YAML %s'\n", sycklval->name));
                        return YAML_VERSION_DIR;
                    }
#line 618 "token.c"
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy35;
		default: goto yy14;
	}
yy38:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy38;
		default: goto yy36;
	}
}
#line 419 "token.re"


Document:
    {
        SyckLevel *lvl = CURRENT_LEVEL();
        if ( lvl->status == syck_lvl_header )
        {
            lvl->status = syck_lvl_doc;
        }

        YYTOKEN = YYCURSOR;


#line 648 "token.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy40;
		case '\t':
		case ' ': goto yy43;
		case '\n': goto yy45;
		case '\r': goto yy47;
		case '!': goto yy48;
		case '"': goto yy49;
		case '#': goto yy50;
		case '&': goto yy51;
		case '\'': goto yy52;
		case '*': goto yy53;
		case ',':
		case ':': goto yy54;
		case '-':
		case '?': goto yy55;
		case '>':
		case '|': goto yy56;
		case '[': goto yy57;
		case ']':
		case '}': goto yy58;
		case '{': goto yy59;
		default: goto yy41;
	}
yy40:
	++YYCURSOR;
#line 538 "token.re"
	{   ENSURE_YAML_IEND(lvl, -1);
                        YYPOS(0);
                        return 0;
                    }
#line 685 "token.c"
yy41:
	++YYCURSOR;
yy42:
#line 543 "token.re"
	{   ENSURE_YAML_IOPEN(lvl, doc_level, 1);
                        goto Plain;
                    }
#line 693 "token.c"
yy43:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\t':
		case ' ': goto yy43;
		default: goto yy44;
	}
yy44:
#line 536 "token.re"
	{   goto Document; }
#line 706 "token.c"
yy45:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n':
		case ' ': goto yy45;
		case '\r': goto yy60;
		default: goto yy46;
	}
yy46:
#line 433 "token.re"
	{   /* Isolate spaces */
                        int indt_len;
                        GOBBLE_UP_YAML_INDENT( indt_len, YYTOKEN );
                        lvl = CURRENT_LEVEL();
                        doc_level = 0;

                        /* XXX: Comment lookahead */
                        if ( *YYCURSOR == '#' )
                        {
                            goto Document;
                        }

                        /* Ignore indentation inside inlines */
                        if ( lvl->status == syck_lvl_iseq || lvl->status == syck_lvl_imap )
                        {
                            goto Document;
                        }

                        /* Check for open indent */
                        ENSURE_YAML_IEND(lvl, indt_len);
                        ENSURE_YAML_IOPEN(lvl, indt_len, 0);
                        if ( indt_len == -1 )
                        {
                            return 0;
                        }
                        return YAML_INDENT;
                    }
#line 747 "token.c"
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy45;
		default: goto yy42;
	}
yy48:
	++YYCURSOR;
#line 517 "token.re"
	{   goto TransferMethod; }
#line 758 "token.c"
yy49:
	++YYCURSOR;
#line 522 "token.re"
	{   ENSURE_YAML_IOPEN(lvl, doc_level, 1);
                        goto DoubleQuote; }
#line 764 "token.c"
yy50:
	++YYCURSOR;
#line 532 "token.re"
	{   eat_comments( parser );
                        goto Document;
                    }
#line 771 "token.c"
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy62;
		default: goto yy42;
	}
yy52:
	++YYCURSOR;
#line 519 "token.re"
	{   ENSURE_YAML_IOPEN(lvl, doc_level, 1);
                        goto SingleQuote; }
#line 846 "token.c"
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy64;
		default: goto yy42;
	}
yy54:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy66;
		case '\r': goto yy68;
		case ' ': goto yy69;
		default: goto yy42;
	}
yy55:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy70;
		case '\r': goto yy72;
		case ' ': goto yy73;
		default: goto yy42;
	}
yy56:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy74;
		case '\r': goto yy76;
		case ' ': goto yy77;
		case '+':
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy78;
		default: goto yy42;
	}
yy57:
	++YYCURSOR;
#line 461 "token.re"
	{   ENSURE_YAML_IOPEN(lvl, doc_level, 1);
                        lvl = CURRENT_LEVEL();
                        ADD_LEVEL(lvl->spaces + 1, syck_lvl_iseq);
                        return YYTOKEN[0];
                    }
#line 963 "token.c"
yy58:
	++YYCURSOR;
#line 473 "token.re"
	{   POP_LEVEL();
                        return YYTOKEN[0];
                    }
#line 970 "token.c"
yy59:
	++YYCURSOR;
#line 467 "token.re"
	{   ENSURE_YAML_IOPEN(lvl, doc_level, 1);
                        lvl = CURRENT_LEVEL();
                        ADD_LEVEL(lvl->spaces + 1, syck_lvl_imap);
                        return YYTOKEN[0];
                    }
#line 979 "token.c"
yy60:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n': goto yy45;
		default: goto yy61;
	}
yy61:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy46;
	} else {
		goto yy42;
	}
yy62:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy62;
		default: goto yy63;
	}
yy63:
#line 499 "token.re"
	{   sycklval->name = syck_strndup( YYTOKEN + 1, YYCURSOR - YYTOKEN - 1 );
                        DPRINTF ((stderr, "DEBUG Anchor '%s' %p\n", sycklval->name, sycklval->name));

                        /*
                         * Remove previous anchors of the same name.  Since the parser will likely
                         * construct deeper nodes first, we want those nodes to be placed in the
                         * queue for matching at a higher level of indentation.
                         */
                        syck_hdlr_remove_anchor(parser, sycklval->name);
                        return YAML_ANCHOR;
                    }
#line 1079 "token.c"
yy64:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy64;
		default: goto yy65;
	}
yy65:
#line 511 "token.re"
	{   ENSURE_YAML_IOPEN(lvl, doc_level, 1);
                        sycklval->name = syck_strndup( YYTOKEN + 1, YYCURSOR - YYTOKEN - 1 );
                        DPRINTF ((stderr, "DEBUG Alias '%s'\n", sycklval->name));
                        return YAML_ALIAS;
                    }
#line 1158 "token.c"
yy66:
	++YYCURSOR;
yy67:
#line 477 "token.re"
	{   if ( *YYTOKEN == ':' && lvl->status != syck_lvl_imap && lvl->status != syck_lvl_iseq )
                        {
                            lvl->status = syck_lvl_map;
                        }
                        YYPOS(1);
                        return YYTOKEN[0];
                    }
#line 1170 "token.c"
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy66;
		default: goto yy61;
	}
yy69:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy69;
		default: goto yy67;
	}
yy70:
	++YYCURSOR;
yy71:
#line 485 "token.re"
	{   ENSURE_YAML_IOPEN(lvl, YYTOKEN - YYLINEPTR, 1);
                        FORCE_NEXT_TOKEN(YAML_IOPEN);
                        if ( *YYCURSOR == '#' || is_newline( YYCURSOR ) || is_newline( YYCURSOR - 1 ) )
                        {
                            YYCURSOR--;
                            ADD_LEVEL((YYTOKEN + 1) - YYLINEPTR, syck_lvl_seq);
                        }
                        else /* spaces followed by content uses the space as indentation */
                        {
                            ADD_LEVEL(YYCURSOR - YYLINEPTR, syck_lvl_seq);
                        }
                        return YYTOKEN[0];
                    }
#line 1202 "token.c"
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy70;
		default: goto yy61;
	}
yy73:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy73;
		default: goto yy71;
	}
yy74:
	++YYCURSOR;
yy75:
#line 525 "token.re"
	{   if ( is_newline( YYCURSOR - 1 ) )
                        {
                            YYCURSOR--;
                        }
                        goto ScalarBlock;
                    }
#line 1227 "token.c"
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy74;
		default: goto yy61;
	}
yy77:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy77;
		default: goto yy75;
	}
yy78:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n': goto yy74;
		case '\r': goto yy76;
		case ' ': goto yy77;
		case '+':
		case '-':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy78;
		default: goto yy61;
	}
}
#line 547 "token.re"

    }

Directive:
    {
        YYTOKTMP = YYCURSOR;


#line 1274 "token.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 11) YYFILL(11);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy80;
		case '\t':
		case ' ': goto yy83;
		case '%': goto yy85;
		default: goto yy81;
	}
yy80:
	YYCURSOR = YYMARKER;
	goto yy82;
yy81:
	++YYCURSOR;
yy82:
#line 562 "token.re"
	{   YYCURSOR = YYTOKTMP;
                        return YAML_DOCSEP;
                    }
#line 1296 "token.c"
yy83:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\t':
		case ' ': goto yy83;
		default: goto yy84;
	}
yy84:
#line 558 "token.re"
	{   goto Directive; }
#line 1309 "token.c"
yy85:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy86;
		case 'Y': goto yy88;
		default: goto yy82;
	}
yy86:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
yy87:
	switch (yych) {
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy86;
		case ':': goto yy89;
		default: goto yy80;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A': goto yy90;
		default: goto yy87;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy91;
		default: goto yy80;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'M': goto yy93;
		default: goto yy87;
	}
yy91:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy91;
		default: goto yy92;
	}
yy92:
#line 556 "token.re"
	{   goto Directive; }
#line 1654 "token.c"
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy94;
		default: goto yy87;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy95;
		default: goto yy87;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1': goto yy96;
		default: goto yy80;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy97;
		default: goto yy80;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy98;
		default: goto yy80;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy99;
		case '\r': goto yy101;
		case ' ': goto yy102;
		default: goto yy80;
	}
yy99:
	++YYCURSOR;
yy100:
#line 560 "token.re"
	{   goto Directive; }
#line 1708 "token.c"
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy99;
		default: goto yy80;
	}
yy102:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy102;
		default: goto yy100;
	}
}
#line 565 "token.re"


    }

Plain:
    {
        int qidx = 0;
        int qcapa = 100;
        char *qstr = S_ALLOC_N( char, qcapa );
        SyckLevel *plvl;
        int parentIndent;

        YYCURSOR = YYTOKEN;
        plvl = CURRENT_LEVEL();
        GET_TRUE_YAML_INDENT(parentIndent);

Plain2:
        YYTOKEN = YYCURSOR;

Plain3:


#line 1747 "token.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy104;
		case '\t': goto yy107;
		case '\n': goto yy109;
		case '\r': goto yy111;
		case ' ': goto yy112;
		case ',': goto yy113;
		case ':': goto yy114;
		case ']': goto yy115;
		case '}': goto yy116;
		default: goto yy105;
	}
yy104:
	++YYCURSOR;
#line 661 "token.re"
	{   RETURN_IMPLICIT(); }
#line 1769 "token.c"
yy105:
	++YYCURSOR;
yy106:
#line 673 "token.re"
	{   QUOTECATS(qstr, qcapa, qidx, YYTOKEN, YYCURSOR - YYTOKEN);
                        goto Plain2;
                    }
#line 1777 "token.c"
yy107:
	++YYCURSOR;
yy108:
#line 663 "token.re"
	{   if ( qidx == 0 )
                        {
                            goto Plain2;
                        }
                        else
                        {
                            goto Plain3;
                        }
                    }
#line 1791 "token.c"
yy109:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n':
		case ' ': goto yy109;
		case '\r': goto yy117;
		default: goto yy110;
	}
yy110:
#line 588 "token.re"
	{   int indt_len, nl_count = 0;
                        char *tok = YYTOKEN;
                        GOBBLE_UP_YAML_INDENT( indt_len, tok );

                        if ( indt_len <= parentIndent )
                        {
                            RETURN_IMPLICIT();
                        }

                        while ( YYTOKEN < YYCURSOR )
                        {
                            int nl_len = newline_len( YYTOKEN++ );
                            if ( nl_len )
                            {
                                nl_count++;
                                YYTOKEN += nl_len - 1;
                            }
                        }
                        if ( nl_count <= 1 )
                        {
                            QUOTECAT(qstr, qcapa, qidx, ' ');
                        }
                        else
                        {
                            int i;
                            for ( i = 0; i < nl_count - 1; i++ )
                            {
                                QUOTECAT(qstr, qcapa, qidx, '\n');
                            }
                        }

                        goto Plain2;
                    }
#line 1838 "token.c"
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy109;
		default: goto yy106;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
		case '#': goto yy119;
		default: goto yy108;
	}
yy113:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy120;
		case '\r': goto yy122;
		case ' ': goto yy123;
		default: goto yy106;
	}
yy114:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy124;
		case '\r': goto yy126;
		case ' ': goto yy127;
		default: goto yy106;
	}
yy115:
	++YYCURSOR;
#line 646 "token.re"
	{   if ( plvl->status != syck_lvl_iseq )
                        {
                            PLAIN_NOT_INL();
                        }
                        else
                        {
                            PLAIN_IS_INL();
                        }
                        RETURN_IMPLICIT();
                    }
#line 1882 "token.c"
yy116:
	++YYCURSOR;
#line 635 "token.re"
	{   if ( plvl->status != syck_lvl_imap )
                        {
                            PLAIN_NOT_INL();
                        }
                        else
                        {
                            PLAIN_IS_INL();
                        }
                        RETURN_IMPLICIT();
                    }
#line 1896 "token.c"
yy117:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n': goto yy109;
		default: goto yy118;
	}
yy118:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy110;
	} else {
		goto yy106;
	}
yy119:
	++YYCURSOR;
#line 657 "token.re"
	{   eat_comments( parser );
                        RETURN_IMPLICIT();
                    }
#line 1918 "token.c"
yy120:
	++YYCURSOR;
yy121:
#line 624 "token.re"
	{   if ( plvl->status != syck_lvl_iseq && plvl->status != syck_lvl_imap )
                        {
                            PLAIN_NOT_INL();
                        }
                        else
                        {
                            PLAIN_IS_INL();
                        }
                        RETURN_IMPLICIT();
                    }
#line 1933 "token.c"
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy120;
		default: goto yy118;
	}
yy123:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy123;
		default: goto yy121;
	}
yy124:
	++YYCURSOR;
yy125:
#line 622 "token.re"
	{   RETURN_IMPLICIT(); }
#line 1953 "token.c"
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy124;
		default: goto yy118;
	}
yy127:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy127;
		default: goto yy125;
	}
}
#line 677 "token.re"

    }

SingleQuote:
    {
        int qidx = 0;
        int qcapa = 100;
        char *qstr = S_ALLOC_N( char, qcapa );

SingleQuote2:
        YYTOKEN = YYCURSOR;


#line 1983 "token.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy129;
		case '\n': goto yy133;
		case '\r': goto yy135;
		case '\'': goto yy136;
		default: goto yy131;
	}
yy129:
	++YYCURSOR;
yy130:
#line 735 "token.re"
	{   SyckLevel *lvl;
                        SyckNode *n = syck_alloc_str();
                        lvl = CURRENT_LEVEL();

                        if ( lvl->status == syck_lvl_str )
                        {
                            POP_LEVEL();
                        }
                        if ( ((SyckParser *)parser)->taguri_expansion == 1 )
                        {
                            n->type_id = syck_taguri( YAML_DOMAIN, "str", 3 );
                        }
                        else
                        {
                            n->type_id = syck_strndup( "str", 3 );
                        }
                        n->data.str->ptr = qstr;
                        n->data.str->len = qidx;
                        n->data.str->style = scalar_1quote;
                        sycklval->nodeData = n;
                        return YAML_PLAIN;
                    }
#line 2021 "token.c"
yy131:
	++YYCURSOR;
yy132:
#line 758 "token.re"
	{   QUOTECAT(qstr, qcapa, qidx, *(YYCURSOR - 1));
                        goto SingleQuote2;
                    }
#line 2029 "token.c"
yy133:
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n':
		case ' ': goto yy133;
		case '\r': goto yy137;
		default: goto yy134;
	}
yy134:
#line 691 "token.re"
	{   int indt_len;
                        int nl_count = 0;
                        SyckLevel *lvl;
                        GOBBLE_UP_YAML_INDENT( indt_len, YYTOKEN );
                        lvl = CURRENT_LEVEL();

                        if ( lvl->status != syck_lvl_str )
                        {
                            ADD_LEVEL( indt_len, syck_lvl_str );
                        }
                        else if ( indt_len < lvl->spaces )
                        {
                            /* Error! */
                        }

                        while ( YYTOKEN < YYCURSOR )
                        {
                            int nl_len = newline_len( YYTOKEN++ );
                            if ( nl_len )
                            {
                                nl_count++;
                                YYTOKEN += nl_len - 1;
                            }
                        }
                        if ( nl_count <= 1 )
                        {
                            QUOTECAT(qstr, qcapa, qidx, ' ');
                        }
                        else
                        {
                            int i;
                            for ( i = 0; i < nl_count - 1; i++ )
                            {
                                QUOTECAT(qstr, qcapa, qidx, '\n');
                            }
                        }

                        goto SingleQuote2;
                    }
#line 2081 "token.c"
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy133;
		default: goto yy132;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\'': goto yy139;
		default: goto yy130;
	}
yy137:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n': goto yy133;
		default: goto yy138;
	}
yy138:
	YYCURSOR = YYMARKER;
	goto yy134;
yy139:
	++YYCURSOR;
#line 731 "token.re"
	{   QUOTECAT(qstr, qcapa, qidx, '\'');
                        goto SingleQuote2;
                    }
#line 2111 "token.c"
}
#line 762 "token.re"


    }


DoubleQuote:
    {
        int keep_nl = 1;
        int qidx = 0;
        int qcapa = 100;
        char *qstr = S_ALLOC_N( char, qcapa );

DoubleQuote2:
        YYTOKEN = YYCURSOR;



#line 2131 "token.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00:
		case '"': goto yy141;
		case '\n': goto yy144;
		case '\r': goto yy146;
		case '\\': goto yy147;
		default: goto yy142;
	}
yy141:
	++YYCURSOR;
#line 843 "token.re"
	{   SyckLevel *lvl;
                        SyckNode *n = syck_alloc_str();
                        lvl = CURRENT_LEVEL();

                        if ( lvl->status == syck_lvl_str )
                        {
                            POP_LEVEL();
                        }
                        if ( ((SyckParser *)parser)->taguri_expansion == 1 )
                        {
                            n->type_id = syck_taguri( YAML_DOMAIN, "str", 3 );
                        }
                        else
                        {
                            n->type_id = syck_strndup( "str", 3 );
                        }
                        n->data.str->ptr = qstr;
                        n->data.str->len = qidx;
                        n->data.str->style = scalar_2quote;
                        sycklval->nodeData = n;
                        return YAML_PLAIN;
                    }
#line 2170 "token.c"
yy142:
	++YYCURSOR;
yy143:
#line 866 "token.re"
	{   QUOTECAT(qstr, qcapa, qidx, *(YYCURSOR - 1));
                        goto DoubleQuote2;
                    }
#line 2178 "token.c"
yy144:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n':
		case ' ': goto yy144;
		case '\r': goto yy148;
		default: goto yy145;
	}
yy145:
#line 780 "token.re"
	{   int indt_len;
                        int nl_count = 0;
                        SyckLevel *lvl;
                        GOBBLE_UP_YAML_INDENT( indt_len, YYTOKEN );
                        lvl = CURRENT_LEVEL();

                        if ( lvl->status != syck_lvl_str )
                        {
                            ADD_LEVEL( indt_len, syck_lvl_str );
                        }
                        else if ( indt_len < lvl->spaces )
                        {
                            /* FIXME */
                        }

                        if ( keep_nl == 1 )
                        {
                            while ( YYTOKEN < YYCURSOR )
                            {
                                int nl_len = newline_len( YYTOKEN++ );
                                if ( nl_len )
                                {
                                    nl_count++;
                                    YYTOKEN += nl_len - 1;
                                }
                            }
                            if ( nl_count <= 1 )
                            {
                                QUOTECAT(qstr, qcapa, qidx, ' ');
                            }
                            else
                            {
                                int i;
                                for ( i = 0; i < nl_count - 1; i++ )
                                {
                                    QUOTECAT(qstr, qcapa, qidx, '\n');
                                }
                            }
                        }

                        keep_nl = 1;
                        goto DoubleQuote2;
                    }
#line 2235 "token.c"
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy144;
		default: goto yy143;
	}
yy147:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '\n': goto yy150;
		case '\r': goto yy151;
		case ' ': goto yy152;
		case '"':
		case '0':
		case '\\':
		case 'a':
		case 'b':
		case 'e':
		case 'f':
		case 'n':
		case 'r':
		case 't':
		case 'v': goto yy153;
		case 'x': goto yy154;
		default: goto yy143;
	}
yy148:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n': goto yy144;
		default: goto yy149;
	}
yy149:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy145;
	} else {
		goto yy143;
	}
yy150:
	++YYCURSOR;
#line 838 "token.re"
	{   keep_nl = 0;
                        YYCURSOR--;
                        goto DoubleQuote2;
                    }
#line 2285 "token.c"
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy150;
		default: goto yy149;
	}
yy152:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n': goto yy150;
		case '\r': goto yy151;
		case ' ': goto yy152;
		default: goto yy149;
	}
yy153:
	++YYCURSOR;
#line 824 "token.re"
	{   char ch = *( YYCURSOR - 1 );
                        QUOTECAT(qstr, qcapa, qidx, escape_seq( ch ));
                        goto DoubleQuote2;
                    }
#line 2309 "token.c"
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy155;
		default: goto yy149;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy156;
		default: goto yy149;
	}
yy156:
	++YYCURSOR;
#line 829 "token.re"
	{   long ch;
                        char *chr_text = syck_strndup( YYTOKEN, 4 );
                        chr_text[0] = '0';
                        ch = strtol( chr_text, NULL, 16 );
                        free( chr_text );
                        QUOTECAT(qstr, qcapa, qidx, ch);
                        goto DoubleQuote2;
                    }
#line 2375 "token.c"
}
#line 870 "token.re"

    }

TransferMethod:
    {
        int qidx = 0;
        int qcapa = 100;
        char *qstr = S_ALLOC_N( char, qcapa );

TransferMethod2:
        YYTOKTMP = YYCURSOR;


#line 2391 "token.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00:
		case '\n': goto yy158;
		case '\r': goto yy162;
		case ' ': goto yy163;
		case '\\': goto yy164;
		default: goto yy160;
	}
yy158:
	++YYCURSOR;
yy159:
#line 883 "token.re"
	{   SyckLevel *lvl;
                        YYCURSOR = YYTOKTMP;
                        if ( YYCURSOR == YYTOKEN + 1 )
                        {
                            free( qstr );
                            return YAML_ITRANSFER;
                        }

                        lvl = CURRENT_LEVEL();

                        /*
                         * URL Prefixing
                         */
                        if ( *qstr == '^' )
                        {
                            sycklval->name = S_ALLOC_N( char, qidx + strlen( lvl->domain ) );
                            sycklval->name[0] = '\0';
                            strcat( sycklval->name, lvl->domain );
                            strncat( sycklval->name, qstr + 1, qidx - 1 );
                            free( qstr );
                        }
                        else
                        {
                            char *carat = qstr;
                            char *qend = qstr + qidx;
                            while ( (++carat) < qend )
                            {
                                if ( *carat == '^' )
                                    break;
                            }

                            if ( carat < qend )
                            {
                                free( lvl->domain );
                                lvl->domain = syck_strndup( qstr, carat - qstr );
                                sycklval->name = S_ALLOC_N( char, ( qend - carat ) + strlen( lvl->domain ) );
                                sycklval->name[0] = '\0';
                                strcat( sycklval->name, lvl->domain );
                                strncat( sycklval->name, carat + 1, ( qend - carat ) - 1 );
                                free( qstr );
                            }
                            else
                            {
                                sycklval->name = qstr;
                            }
                        }

                        DPRINTF ((stderr, "DEBUG Transfer name '%s'\n", sycklval->name));
                        return YAML_TRANSFER;
                    }
#line 2458 "token.c"
yy160:
	++YYCURSOR;
yy161:
#line 951 "token.re"
	{   QUOTECAT(qstr, qcapa, qidx, *(YYCURSOR - 1));
                        goto TransferMethod2;
                    }
#line 2466 "token.c"
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy158;
		default: goto yy161;
	}
yy163:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy163;
		default: goto yy159;
	}
yy164:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '"':
		case '0':
		case '\\':
		case 'a':
		case 'b':
		case 'e':
		case 'f':
		case 'n':
		case 'r':
		case 't':
		case 'v': goto yy165;
		case 'x': goto yy166;
		default: goto yy161;
	}
yy165:
	++YYCURSOR;
#line 937 "token.re"
	{  char ch = *( YYCURSOR - 1 );
                        QUOTECAT(qstr, qcapa, qidx, escape_seq( ch ));
                        goto TransferMethod2;
                    }
#line 2505 "token.c"
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy168;
		default: goto yy167;
	}
yy167:
	YYCURSOR = YYMARKER;
	goto yy161;
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy169;
		default: goto yy167;
	}
yy169:
	++YYCURSOR;
#line 942 "token.re"
	{   long ch;
                        char *chr_text = syck_strndup( YYTOKTMP, 4 );
                        chr_text[0] = '0';
                        ch = strtol( chr_text, NULL, 16 );
                        free( chr_text );
                        QUOTECAT(qstr, qcapa, qidx, ch);
                        goto TransferMethod2;
                    }
#line 2574 "token.c"
}
#line 954 "token.re"

    }

ScalarBlock:
    {
        int qidx = 0;
        int qcapa = 100;
        char *qstr = S_ALLOC_N( char, qcapa );
        int blockType = 0;
        int nlDoWhat = 0;
        int lastIndent = 0;
        int forceIndent = -1;
        char *yyt = YYTOKEN;
        SyckLevel *lvl = CURRENT_LEVEL();
        int parentIndent = -1;

        switch ( *yyt )
        {
            case '|': blockType = BLOCK_LIT; break;
            case '>': blockType = BLOCK_FOLD; break;
            default: break;
        }

        while ( ++yyt <= YYCURSOR )
        {
            if ( *yyt == '-' )
            {
                nlDoWhat = NL_CHOMP;
            }
            else if ( *yyt == '+' )
            {
                nlDoWhat = NL_KEEP;
            }
            else if ( isdigit( *yyt ) )
            {
                forceIndent = strtol( yyt, NULL, 10 );
            }
        }

        qstr[0] = '\0';
        YYTOKEN = YYCURSOR;

ScalarBlock2:
        YYTOKEN = YYCURSOR;


#line 2623 "token.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 13) YYFILL(13);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy171;
		case '\n': goto yy174;
		case '\r': goto yy176;
		case '#': goto yy177;
		case '%': goto yy178;
		case '-': goto yy179;
		default: goto yy172;
	}
yy171:
	++YYCURSOR;
#line 1091 "token.re"
	{   YYCURSOR--;
                        POP_LEVEL();
                        RETURN_YAML_BLOCK();
                    }
#line 2645 "token.c"
yy172:
	++YYCURSOR;
yy173:
#line 1119 "token.re"
	{   QUOTECAT(qstr, qcapa, qidx, *YYTOKEN);
                        goto ScalarBlock2;
                    }
#line 2653 "token.c"
yy174:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n':
		case ' ': goto yy174;
		case '\r': goto yy180;
		default: goto yy175;
	}
yy175:
#line 1001 "token.re"
	{   char *pacer;
                        char *tok = YYTOKEN;
                        int indt_len = 0, nl_count = 0, fold_nl = 0, nl_begin = 0;
                        GOBBLE_UP_YAML_INDENT( indt_len, tok );
                        lvl = CURRENT_LEVEL();

                        if ( lvl->status != syck_lvl_block )
                        {
                            GET_TRUE_YAML_INDENT(parentIndent);
                            if ( forceIndent > 0 ) forceIndent += parentIndent;
                            if ( indt_len > parentIndent )
                            {
                                int new_spaces = forceIndent > 0 ? forceIndent : indt_len;
                                ADD_LEVEL( new_spaces, syck_lvl_block );
                                lastIndent = indt_len - new_spaces;
                                nl_begin = 1;
                                lvl = CURRENT_LEVEL();
                            }
                            else
                            {
                                YYCURSOR = YYTOKEN;
                                RETURN_YAML_BLOCK();
                            }
                        }

                        /*
                         * Fold only in the event of two lines being on the leftmost
                         * indentation.
                         */
                        if ( blockType == BLOCK_FOLD && lastIndent == 0 && ( indt_len - lvl->spaces ) == 0 )
                        {
                            fold_nl = 1;
                        }

                        pacer = YYTOKEN;
                        while ( pacer < YYCURSOR )
                        {
                            int nl_len = newline_len( pacer++ );
                            if ( nl_len )
                            {
                                nl_count++;
                                pacer += nl_len - 1;
                            }
                        }

                        if ( fold_nl == 1 || nl_begin == 1 )
                        {
                            nl_count--;
                        }

                        if ( nl_count < 1 && nl_begin == 0 )
                        {
                            QUOTECAT(qstr, qcapa, qidx, ' ');
                        }
                        else
                        {
                            int i;
                            for ( i = 0; i < nl_count; i++ )
                            {
                                QUOTECAT(qstr, qcapa, qidx, '\n');
                            }
                        }

                        lastIndent = indt_len - lvl->spaces;
                        YYCURSOR -= lastIndent;

                        if ( indt_len < lvl->spaces )
                        {
                            POP_LEVEL();
                            YYCURSOR = YYTOKEN;
                            RETURN_YAML_BLOCK();
                        }
                        goto ScalarBlock2;
                    }
#line 2741 "token.c"
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy174;
		default: goto yy173;
	}
yy177:
	++YYCURSOR;
#line 1077 "token.re"
	{   lvl = CURRENT_LEVEL();
                        if ( lvl->status != syck_lvl_block )
                        {
                            eat_comments( parser );
                            YYTOKEN = YYCURSOR;
                        }
                        else
                        {
                            QUOTECAT(qstr, qcapa, qidx, *YYTOKEN);
                        }
                        goto ScalarBlock2;
                    }
#line 2763 "token.c"
yy178:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'Y': goto yy182;
		default: goto yy173;
	}
yy179:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '-': goto yy183;
		default: goto yy173;
	}
yy180:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n': goto yy174;
		default: goto yy181;
	}
yy181:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
		case 0: goto yy175;
		case 1: goto yy173;
		default: goto yy200;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'A': goto yy184;
		default: goto yy181;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy185;
		default: goto yy181;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'M': goto yy186;
		default: goto yy181;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy187;
		case '\r': goto yy189;
		case ' ': goto yy190;
		default: goto yy181;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'L': goto yy191;
		default: goto yy181;
	}
yy187:
	++YYCURSOR;
yy188:
#line 1096 "token.re"
	{   if ( YYTOKEN == YYLINEPTR )
                        {
                            if ( blockType == BLOCK_FOLD && qidx > 0 )
                            {
                                qidx -= 1;
                            }
                            QUOTECAT(qstr, qcapa, qidx, '\n');
                            POP_LEVEL();
                            YYCURSOR = YYTOKEN;
                            RETURN_YAML_BLOCK();
                        }
                        else
                        {
                            QUOTECAT(qstr, qcapa, qidx, *YYTOKEN);
                            YYCURSOR = YYTOKEN + 1;
                            goto ScalarBlock2;
                        }
                    }
#line 2847 "token.c"
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy187;
		default: goto yy181;
	}
yy190:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy190;
		default: goto yy188;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy192;
		default: goto yy181;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1': goto yy193;
		default: goto yy181;
	}
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy194;
		default: goto yy181;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy195;
		default: goto yy181;
	}
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy196;
		case '\r': goto yy197;
		case ' ': goto yy198;
		default: goto yy181;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy199;
		case '\r': goto yy201;
		case ' ': goto yy202;
		default: goto yy181;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy196;
		default: goto yy181;
	}
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy199;
		case '\r': goto yy201;
		case ' ': goto yy203;
		default: goto yy181;
	}
yy199:
	++YYCURSOR;
yy200:
#line 1115 "token.re"
	{   YYCURSOR = YYTOKEN;
                        return YAML_VERSION_DIR;
                    }
#line 2933 "token.c"
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy199;
		default: goto yy181;
	}
yy202:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case ' ': goto yy202;
		default: goto yy200;
	}
yy203:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n': goto yy199;
		case '\r': goto yy201;
		case ' ': goto yy203;
		default: goto yy200;
	}
}
#line 1124 "token.re"

    }

    return 0;

}

static void
eat_comments( SyckParser *parser )
{
Comment:
    {
        YYTOKEN = YYCURSOR;


#line 2976 "token.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy205;
		case '\n': goto yy209;
		case '\r': goto yy210;
		default: goto yy207;
	}
yy205:
	++YYCURSOR;
yy206:
#line 1140 "token.re"
	{   YYCURSOR = YYTOKEN;
                        return;
                    }
#line 2994 "token.c"
yy207:
	++YYCURSOR;
yy208:
#line 1144 "token.re"
	{   goto Comment;
                    }
#line 3001 "token.c"
yy209:
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n': goto yy209;
		case '\r': goto yy211;
		default: goto yy206;
	}
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\n': goto yy209;
		default: goto yy208;
	}
yy211:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '\n': goto yy209;
		default: goto yy212;
	}
yy212:
	YYCURSOR = YYMARKER;
	goto yy206;
}
#line 1147 "token.re"


    }

}

int
syckwrap(void)
{
    return 1;
}

void
syckerror( SyckParser *parser, const char *msg )
{
    if ( parser->error_handler == NULL )
        parser->error_handler = syck_default_error_handler;

    parser->root = parser->root_on_error;
    DPRINTF ((stderr, "DEBUG %s root=%lu\n", __FUNCTION__, parser->root));
    (parser->error_handler)(parser, msg);
}

